<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\ElectionDistrict;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ElectionDistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('election_districts')->insert([
            [
                'name_tm' => '1-nji «Garaşsyzlyk» saýlaw okrugy', 'name_ru' => '1-nji «Garaşsyzlyk» saýlaw okrugy', 'name_en' => '1-nji «Garaşsyzlyk» saýlaw okrugy',
                'borders_tm' => "Berkararlyk etrabynyň Gurbansoltan eje şaýolunyň S.Türkmenbaşy şaýoly bilen kesişýän çatrygyndan başlap, Gurbansoltan eje şaýolunyň ugry bilen B.Annanow köçesine çenli, şol ýerden B.Annanow köçesiniň ugry bilen A.Nyýazow şaýoluna çenli, A.Nyýazow şaýolunyň ugry bilen A.Garlyýew köçesine çenli, A.Garlyýew köçesiniň ugry bilen Galkynyş köçesine çenli, Galkynyş köçesiniň ugry bilen S.Türkmenbaşy şaýoluna çenli,  S.Türkmenbaşy şaýolunyň ugry bilen Gurbansoltan eje şaýoluna çenli araçäkleri öz içine alýar", 
                'borders_ru' => 'Berkararlyk etrabynyň Gurbansoltan eje şaýolunyň S.Türkmenbaşy şaýoly bilen kesişýän çatrygyndan başlap, Gurbansoltan eje şaýolunyň ugry bilen B.Annanow köçesine çenli, şol ýerden B.Annanow köçesiniň ugry bilen A.Nyýazow şaýoluna çenli, A.Nyýazow şaýolunyň ugry bilen A.Garlyýew köçesine çenli, A.Garlyýew köçesiniň ugry bilen Galkynyş köçesine çenli, Galkynyş köçesiniň ugry bilen S.Türkmenbaşy şaýoluna çenli,  S.Türkmenbaşy şaýolunyň ugry bilen Gurbansoltan eje şaýoluna çenli araçäkleri öz içine alýar', 
                'borders_en' => 'Berkararlyk etrabynyň Gurbansoltan eje şaýolunyň S.Türkmenbaşy şaýoly bilen kesişýän çatrygyndan başlap, Gurbansoltan eje şaýolunyň ugry bilen B.Annanow köçesine çenli, şol ýerden B.Annanow köçesiniň ugry bilen A.Nyýazow şaýoluna çenli, A.Nyýazow şaýolunyň ugry bilen A.Garlyýew köçesine çenli, A.Garlyýew köçesiniň ugry bilen Galkynyş köçesine çenli, Galkynyş köçesiniň ugry bilen S.Türkmenbaşy şaýoluna çenli,  S.Türkmenbaşy şaýolunyň ugry bilen Gurbansoltan eje şaýoluna çenli araçäkleri öz içine alýar',
                'district_number' => 1,
            ],
            [
                'name_tm' => '2-nji «Bitaraplyk» saýlaw okrugy', 'name_ru' => '2-nji «Bitaraplyk» saýlaw okrugy', 'name_en' => '2-nji «Bitaraplyk» saýlaw okrugy',
                'borders_tm' => "Berkararlyk etrabynyň Gündogar köçesiniň N.Halmämmedow köçesi bilen kesişýän çatrygyndan başlap, N.Halmämmedow köçesiniň ugry bilen B.Annanow köçesine çenli, şol ýerden B.Annanow köçesiniň ugry bilen Oguzhan köçesine çenli, Oguzhan köçesiniň ugry bilen A.Garlyýew köçesine çenli, A.Garlyýew köçesiniň ugry bilen A.Nyýazow şaýoluna çenli, A.Nyýazow şaýolunyň ugry bilen B.Annanow köçesine çenli, B.Annanow köçesiniň ugry bilen Gurbansoltan eje şaýoluna çenli, Gurbansoltan eje şaýolunyň ugry bilen Hoja Ahmet Ýasawy köçesine çenli, şol ýerden demir ýoluny kesip geçip, Hoja Ahmet Ýasawy köçesiniň ugry bilen A.Gönübek köçesine çenli, A.Gönübek köçesiniň ugry bilen B.Annanow köçesine çenli, B.Annanow köçesiniň ugry bilen, Garagum derýasyna çenli, şol ýerden Garagum derýasynyň ugry bilen, Ahal welaýatynyň Ak bugdaý etrabynyň araçägine çenli, şol ýerden Ak bugdaý etrabynyň araçäginiň ugry bilen Gurbansoltan eje şaýoluny kesip geçip, Gündogar köçesine çenli, Gündogar köçesiniň ugry bilen N.Halmämmedow köçesine çenli araçäkleri öz içine alýar", 
                'borders_ru' => "Berkararlyk etrabynyň Gündogar köçesiniň N.Halmämmedow köçesi bilen kesişýän çatrygyndan başlap, N.Halmämmedow köçesiniň ugry bilen B.Annanow köçesine çenli, şol ýerden B.Annanow köçesiniň ugry bilen Oguzhan köçesine çenli, Oguzhan köçesiniň ugry bilen A.Garlyýew köçesine çenli, A.Garlyýew köçesiniň ugry bilen A.Nyýazow şaýoluna çenli, A.Nyýazow şaýolunyň ugry bilen B.Annanow köçesine çenli, B.Annanow köçesiniň ugry bilen Gurbansoltan eje şaýoluna çenli, Gurbansoltan eje şaýolunyň ugry bilen Hoja Ahmet Ýasawy köçesine çenli, şol ýerden demir ýoluny kesip geçip, Hoja Ahmet Ýasawy köçesiniň ugry bilen A.Gönübek köçesine çenli, A.Gönübek köçesiniň ugry bilen B.Annanow köçesine çenli, B.Annanow köçesiniň ugry bilen, Garagum derýasyna çenli, şol ýerden Garagum derýasynyň ugry bilen, Ahal welaýatynyň Ak bugdaý etrabynyň araçägine çenli, şol ýerden Ak bugdaý etrabynyň araçäginiň ugry bilen Gurbansoltan eje şaýoluny kesip geçip, Gündogar köçesine çenli, Gündogar köçesiniň ugry bilen N.Halmämmedow köçesine çenli araçäkleri öz içine alýar", 
                'borders_en' => "Berkararlyk etrabynyň Gündogar köçesiniň N.Halmämmedow köçesi bilen kesişýän çatrygyndan başlap, N.Halmämmedow köçesiniň ugry bilen B.Annanow köçesine çenli, şol ýerden B.Annanow köçesiniň ugry bilen Oguzhan köçesine çenli, Oguzhan köçesiniň ugry bilen A.Garlyýew köçesine çenli, A.Garlyýew köçesiniň ugry bilen A.Nyýazow şaýoluna çenli, A.Nyýazow şaýolunyň ugry bilen B.Annanow köçesine çenli, B.Annanow köçesiniň ugry bilen Gurbansoltan eje şaýoluna çenli, Gurbansoltan eje şaýolunyň ugry bilen Hoja Ahmet Ýasawy köçesine çenli, şol ýerden demir ýoluny kesip geçip, Hoja Ahmet Ýasawy köçesiniň ugry bilen A.Gönübek köçesine çenli, A.Gönübek köçesiniň ugry bilen B.Annanow köçesine çenli, B.Annanow köçesiniň ugry bilen, Garagum derýasyna çenli, şol ýerden Garagum derýasynyň ugry bilen, Ahal welaýatynyň Ak bugdaý etrabynyň araçägine çenli, şol ýerden Ak bugdaý etrabynyň araçäginiň ugry bilen Gurbansoltan eje şaýoluny kesip geçip, Gündogar köçesine çenli, Gündogar köçesiniň ugry bilen N.Halmämmedow köçesine çenli araçäkleri öz içine alýar", 
                'district_number' => 2,
            ],
            [
                'name_tm' => '3-nji «Azatlyk» saýlaw okrugy', 'name_ru' => '3-nji «Azatlyk» saýlaw okrugy', 'name_en' => '3-nji «Azatlyk» saýlaw okrugy',
                'borders_tm' => "Berkararlyk etrabynyň Gurbansoltan eje şaýolunyň Tahyrow köçesi bilen kesişýän çatrygyndan başlap, Tahyrow köçesiniň ugry bilen S.Ataýewa köçesine çenli, şol ýerden S.Ataýewa köçesiniň ugry bilen G.Bäşiýew köçesine çenli, G.Bäşiýew köçesiniň ugry bilen G.Gulyýew köçesine çenli, G.Gulyýew köçesiniň ugry bilen Bagtyýarlyk etrabynyň araçägine çenli, şol ýerden Bagtyýarlyk etrabynyň araçäginiň ugry bilen Altyn suw köçesine çenli, şol ýerden Garadamak we Şor ýaşaýyş toplumlaryny öz içine alyp, Garagum derýasyna çenli, şol ýerden Garagum derýasyny kesip geçip, B.Annanow köçesine çenli, B.Annanow köçesiniň ugry bilen A.Gönübek köçesine çenli, A.Gönübek köçesiniň ugry bilen, Hoja Ahmet Ýasawy köçesine çenli, Hoja Ahmet Ýasawy köçesiniň ugry bilen demir ýoluny kesip geçip, Gurbansoltan eje şaýoluna çenli, Gurbansoltan eje şaýolunyň ugry bilen Tahyrow köçesine çenli araçäkleri öz içine alýar", 
                'borders_ru' => "Berkararlyk etrabynyň Gurbansoltan eje şaýolunyň Tahyrow köçesi bilen kesişýän çatrygyndan başlap, Tahyrow köçesiniň ugry bilen S.Ataýewa köçesine çenli, şol ýerden S.Ataýewa köçesiniň ugry bilen G.Bäşiýew köçesine çenli, G.Bäşiýew köçesiniň ugry bilen G.Gulyýew köçesine çenli, G.Gulyýew köçesiniň ugry bilen Bagtyýarlyk etrabynyň araçägine çenli, şol ýerden Bagtyýarlyk etrabynyň araçäginiň ugry bilen Altyn suw köçesine çenli, şol ýerden Garadamak we Şor ýaşaýyş toplumlaryny öz içine alyp, Garagum derýasyna çenli, şol ýerden Garagum derýasyny kesip geçip, B.Annanow köçesine çenli, B.Annanow köçesiniň ugry bilen A.Gönübek köçesine çenli, A.Gönübek köçesiniň ugry bilen, Hoja Ahmet Ýasawy köçesine çenli, Hoja Ahmet Ýasawy köçesiniň ugry bilen demir ýoluny kesip geçip, Gurbansoltan eje şaýoluna çenli, Gurbansoltan eje şaýolunyň ugry bilen Tahyrow köçesine çenli araçäkleri öz içine alýar", 
                'borders_en' => "Berkararlyk etrabynyň Gurbansoltan eje şaýolunyň Tahyrow köçesi bilen kesişýän çatrygyndan başlap, Tahyrow köçesiniň ugry bilen S.Ataýewa köçesine çenli, şol ýerden S.Ataýewa köçesiniň ugry bilen G.Bäşiýew köçesine çenli, G.Bäşiýew köçesiniň ugry bilen G.Gulyýew köçesine çenli, G.Gulyýew köçesiniň ugry bilen Bagtyýarlyk etrabynyň araçägine çenli, şol ýerden Bagtyýarlyk etrabynyň araçäginiň ugry bilen Altyn suw köçesine çenli, şol ýerden Garadamak we Şor ýaşaýyş toplumlaryny öz içine alyp, Garagum derýasyna çenli, şol ýerden Garagum derýasyny kesip geçip, B.Annanow köçesine çenli, B.Annanow köçesiniň ugry bilen A.Gönübek köçesine çenli, A.Gönübek köçesiniň ugry bilen, Hoja Ahmet Ýasawy köçesine çenli, Hoja Ahmet Ýasawy köçesiniň ugry bilen demir ýoluny kesip geçip, Gurbansoltan eje şaýoluna çenli, Gurbansoltan eje şaýolunyň ugry bilen Tahyrow köçesine çenli araçäkleri öz içine alýar", 
                'district_number' => 3,
            ],
            [
                'name_tm' => '4-nji «Berkararlyk» saýlaw okrugy', 'name_ru' => '4-nji «Berkararlyk» saýlaw okrugy', 'name_en' => '4-nji «Berkararlyk» saýlaw okrugy',
                'borders_tm' => "Berkararlyk etrabynyň Gündogar köçesiniň N.Halmämmedow köçesi bilen kesişýän çatrygyndan başlap, Gündogar köçesiniň ugry bilen Oguzhan köçesine çenli, şol ýerden Oguzhan köçesiniň ugry bilen B.Annanow köçesine çenli, B.Annanow köçesiniň ugry bilen Arçabil şaýoluna çenli, Arçabil şaýolunyň ugry bilen A.Garlyýew köçesine çenli, A.Garlyýew köçesiniň ugry bilen Oguzhan köçesine çenli,  Oguzhan köçesiniň ugry bilen B.Annanow köçesine çenli, B.Annanow köçesiniň ugry bilen N.Halmämmedow köçesine çenli, N.Halmämmedow köçesiniň ugry bilen Gündogar köçesine çenli araçäkleri öz içine alýar", 
                'borders_ru' => "Berkararlyk etrabynyň Gündogar köçesiniň N.Halmämmedow köçesi bilen kesişýän çatrygyndan başlap, Gündogar köçesiniň ugry bilen Oguzhan köçesine çenli, şol ýerden Oguzhan köçesiniň ugry bilen B.Annanow köçesine çenli, B.Annanow köçesiniň ugry bilen Arçabil şaýoluna çenli, Arçabil şaýolunyň ugry bilen A.Garlyýew köçesine çenli, A.Garlyýew köçesiniň ugry bilen Oguzhan köçesine çenli,  Oguzhan köçesiniň ugry bilen B.Annanow köçesine çenli, B.Annanow köçesiniň ugry bilen N.Halmämmedow köçesine çenli, N.Halmämmedow köçesiniň ugry bilen Gündogar köçesine çenli araçäkleri öz içine alýar", 
                'borders_en' => "Berkararlyk etrabynyň Gündogar köçesiniň N.Halmämmedow köçesi bilen kesişýän çatrygyndan başlap, Gündogar köçesiniň ugry bilen Oguzhan köçesine çenli, şol ýerden Oguzhan köçesiniň ugry bilen B.Annanow köçesine çenli, B.Annanow köçesiniň ugry bilen Arçabil şaýoluna çenli, Arçabil şaýolunyň ugry bilen A.Garlyýew köçesine çenli, A.Garlyýew köçesiniň ugry bilen Oguzhan köçesine çenli,  Oguzhan köçesiniň ugry bilen B.Annanow köçesine çenli, B.Annanow köçesiniň ugry bilen N.Halmämmedow köçesine çenli, N.Halmämmedow köçesiniň ugry bilen Gündogar köçesine çenli araçäkleri öz içine alýar", 
                'district_number' => 4,
            ],
            [
                'name_tm' => '5-nji «Parahatçylyk» saýlaw okrugy ', 'name_ru' => '5-nji «Parahatçylyk» saýlaw okrugy ', 'name_en' => '5-nji «Parahatçylyk» saýlaw okrugy ',
                'borders_tm' => "Köpetdag etrabynyň Bitarap Türkmenistan şaýolunyň Gorkut Ata köçesi bilen kesişýän çatrygyndan başlap, Bitarap Türkmenistan şaýolunyň ugry bilen A.Nyýazow şaýoluna çenli, şol ýerden A.Nyýazow şaýolunyň ugry bilen Magtymguly şaýoluna çenli, Magtymguly şaýolunyň ugry bilen S.Türkmenbaşy şaýoluna çenli, S.Türkmenbaşy şaýolunyň ugry bilen Galkynyş köçesine çenli,  Galkynyş köçesiniň ugry bilen A.Garlyýew köçesine çenli, A.Garlyýew köçesiniň ugry bilen A.Nyýazow şaýoluna çenli, A.Nyýazow şaýolunyň ugry bilen, S.Türkmenbaşy şaýoluna çenli, S.Türkmenbaşy şaýolunyň 79, 83, 83/1, 83/2-nji jaýlaryny, Täjir köçesiniň 4/1, 4/2, 4/3, 4/4-nji jaýlaryny we Oguzhan köçesiniň 102/1, 102/2, 102/3, 106, 108-nji jaýlaryny öz içine alyp, Oguzhan köçesine çenli, şol ýerden Oguzhan köçesiniň ugry bilen Garaşsyzlyk şaýoluna çenli, Garaşsyzlyk şaýolunyň 34, 38, 40, 42, 44, 46, 46/1, 48, 50, 52, 54, 56, 58, 60, 62, 63, 63/1, 65, 67, 67/1, 69, 69/1, 69/2, 71-nji ýaşaýyş jaýlaryny öz içine alyp, Serhowuzly seýilgähiň ugry bilen, Gorkut ata köçesine çenli araçäkleri öz içine alýar", 
                'borders_ru' => "Köpetdag etrabynyň Bitarap Türkmenistan şaýolunyň Gorkut Ata köçesi bilen kesişýän çatrygyndan başlap, Bitarap Türkmenistan şaýolunyň ugry bilen A.Nyýazow şaýoluna çenli, şol ýerden A.Nyýazow şaýolunyň ugry bilen Magtymguly şaýoluna çenli, Magtymguly şaýolunyň ugry bilen S.Türkmenbaşy şaýoluna çenli, S.Türkmenbaşy şaýolunyň ugry bilen Galkynyş köçesine çenli,  Galkynyş köçesiniň ugry bilen A.Garlyýew köçesine çenli, A.Garlyýew köçesiniň ugry bilen A.Nyýazow şaýoluna çenli, A.Nyýazow şaýolunyň ugry bilen, S.Türkmenbaşy şaýoluna çenli, S.Türkmenbaşy şaýolunyň 79, 83, 83/1, 83/2-nji jaýlaryny, Täjir köçesiniň 4/1, 4/2, 4/3, 4/4-nji jaýlaryny we Oguzhan köçesiniň 102/1, 102/2, 102/3, 106, 108-nji jaýlaryny öz içine alyp, Oguzhan köçesine çenli, şol ýerden Oguzhan köçesiniň ugry bilen Garaşsyzlyk şaýoluna çenli, Garaşsyzlyk şaýolunyň 34, 38, 40, 42, 44, 46, 46/1, 48, 50, 52, 54, 56, 58, 60, 62, 63, 63/1, 65, 67, 67/1, 69, 69/1, 69/2, 71-nji ýaşaýyş jaýlaryny öz içine alyp, Serhowuzly seýilgähiň ugry bilen, Gorkut ata köçesine çenli araçäkleri öz içine alýar", 
                'borders_en' => "Köpetdag etrabynyň Bitarap Türkmenistan şaýolunyň Gorkut Ata köçesi bilen kesişýän çatrygyndan başlap, Bitarap Türkmenistan şaýolunyň ugry bilen A.Nyýazow şaýoluna çenli, şol ýerden A.Nyýazow şaýolunyň ugry bilen Magtymguly şaýoluna çenli, Magtymguly şaýolunyň ugry bilen S.Türkmenbaşy şaýoluna çenli, S.Türkmenbaşy şaýolunyň ugry bilen Galkynyş köçesine çenli,  Galkynyş köçesiniň ugry bilen A.Garlyýew köçesine çenli, A.Garlyýew köçesiniň ugry bilen A.Nyýazow şaýoluna çenli, A.Nyýazow şaýolunyň ugry bilen, S.Türkmenbaşy şaýoluna çenli, S.Türkmenbaşy şaýolunyň 79, 83, 83/1, 83/2-nji jaýlaryny, Täjir köçesiniň 4/1, 4/2, 4/3, 4/4-nji jaýlaryny we Oguzhan köçesiniň 102/1, 102/2, 102/3, 106, 108-nji jaýlaryny öz içine alyp, Oguzhan köçesine çenli, şol ýerden Oguzhan köçesiniň ugry bilen Garaşsyzlyk şaýoluna çenli, Garaşsyzlyk şaýolunyň 34, 38, 40, 42, 44, 46, 46/1, 48, 50, 52, 54, 56, 58, 60, 62, 63, 63/1, 65, 67, 67/1, 69, 69/1, 69/2, 71-nji ýaşaýyş jaýlaryny öz içine alyp, Serhowuzly seýilgähiň ugry bilen, Gorkut ata köçesine çenli araçäkleri öz içine alýar", 
                'district_number' => 5,
            ]
        ]);
    }
}
