<?php

namespace Database\Seeders;

use App\Models\TkmAvaza;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TkmAvazaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        TkmAvaza::create([
            'title_tm' => '«AWAZA» MILLI SYÝAHATÇYLYK ZOLAGY',
            'title_ru' => 'ТУРИСТИЧЕСКАЯ ЗОНА «АВАЗА»',
            'title_en' => 'AVAZA NATIONAL TOURIST ZONE',
            
            'content_tm' => 'Hazaryň türkmen böleginde sagaldyş-dynç alyş we ekologiki syýahatçylygy ösdürmeklik ägirt uly mümkinçiliklere eýe bolýar. Häzirki wagtda syýahatçylyk Türkmenistanyň ykdysadyýetiň wajyp ugurlarynyň biri bolmak bilen, ýurduň durmuş-ykdysady taýdan mundan beýläk hem ösmegine ýardam edýär.
                            Tebigatyň özi bu künjek hakynda alada edip, mylaýym howa şertleri, minerally palçyk çeşmeleri we köp kilometrlere uzap gidýän altyn öwüşginli-çägesöw deňiz kenarlary, gözelligi boýunça täsin deňiz görnüşleri, Hazar döwlet goraghanasynyň biologik köpdürliligi bilen tapawutlanýan, şol sanda, suw-batgalyk ýerlerdäki guşlaryň köpdürliligi bilen eçilipdir.
                            2007-nji ýylyň iýun aýynda geçirilen «Awaza» milli syýahatçylyk zolagynyň tanyşdyrylyş dabarasy dünýä möçberinde uly waka boldy hem-de ýurdumyzyň dynç alyş we syýahçylyk industriýasyny ösdürmek boýunça täzeçe çemeleşmäniň aýdyň subutnamasyna öwrüldi. Bu ähmiýetli taslamanyň esasy maksady - Türkmenistanyň durmuş syýasatynyň nukdaýnazaryndan şeýle wajyp taslamany hemmetaraplaýyn amala aşyryp, ýurduň ilatynyň ýaşaýşy üçin zerur bolan şertler bilen doly üpjün etmekden ybarat bolup durýar. Şunuň bilen baglylykda, bu sebitde ulag-aragatnaşyk ulgamynyň, şol sanda, halkara deňiz portunyň we howa menziliniň, awtoulag hem-de demir ýollarynyň barlygy örän ähmiýetlidir.
                            «Awaza» milli syýahatçylyk zolagynyň taslamasyny durmuşa geçirmek üçin umumy meýdany 5000 gektar bolan ýer bölegi bölünip berildi. 2007-nji ýylyň ahyrynda bu syýahatçylyk zolagyň ilkinji desgalarynyň gurluşyklaryna başlanyldy. 2009-njy ýylyň iýunynda Hazar deňziniň kenarynda «Awaza» milli syýahatçylyk zolagynda täze binalaryň açylyş dabarasy boldy.
                            «Awaza» Türkmenistanyň döwlet syýasatynda geljekki onýyllyklar üçin ýurduň strategiki meýilnamasynda aýratyn orny tutýar. Bu taslama milli öwüşgünli döredijilik çözgütleri bilen birlikde dünýä arhitekturasynyň we binagärliginiň, şeýle hem inžener-tehniki pikirleriniň iň öňdebaryjy üstünliklerini utgaşykly amala aşyrmaga ýardam edýär.
                            Häzirki wagtda «Awaza» milli syýahatçylyk zolagynda bir wagtyň özünde dynç alýanlaryň 10 müňden gowragyny kabul edip bilýän 18 sany myhmanhana, 8 sany dynç alyş we sagaldyş merkezleri, şol sanda, 1380 orunlyk çagalar dync alyş merkezler hem-de 9 sany kottejler toplumlary işleýär. Dynç alýanlaryň hyzmatynda 4 sany seýilgäh bolup, olardan 2-si oýun attraksionly seýilgählerdir. Umumy meýdany 83600 inedördül metr bolan teatrlaşdyrylan intraktiw deňiz suw çüwdürümlerini, amfiteatry, çagalar üçin attraksionly oýun meýdançalary, köpsanly kafeleri we restoranlary, gök zolaklary, tehniki desgalary öz içine alýan seýilgähler bu ýerde dynç alýanlaryň hem-de şäheriň ilatynyň iň söýgüli ýerlerine öwrüldi.
                            Beýikligi 40-dan 100 metre çenli bolan suw çüwdürümler toplumy häzirki zaman ýokary tehnologiýalar esasynda sazlaşykly gurlan desgalar hökmünde aýratyn özboluşlylygy bilen tapawutlanýarlar. Deňiz kenaryndan 85 metr daşlykda ýerleşýän boýy 24 metr, ini 60 metr bolan suw çüwdürimleriniň ýüzündäki ekranda dürli görnüşli golografik şekiller we tans edýän sudurlar görünýär we olar seýilgähde goýberilýän saz owazy bilen utgaşykly hereket edip yzygiderli çalyşyp durýar. Deňiz suw çüwdürümlerinden ybarat bolan ekranda görünýän golografik şekilleriň boýy 20 metre ýetip, şekilleri hakyky ýaly edip görkezýär. Deňze tarap gurnalan ýodajyk arkaly 50 metr aralygy geçip, iki tarapa uzap gidýän her tarapynyň uzynlygy 34 metr bolan ýodajykdaky gözegçilik meýdançasyndan gündiz Hazar deňziniň gözelligini, agşamara bolsa ýakyn aralykdaky deňiz suw çüwdürümleriniň hereketlerini synlamak bolýar.
                            2018-nji ýylyň iýulynda umumy meýdany 30 gektar bolan akwapark ulanylyşa berildi. Akwaparkyň düzümine suw attraksionlary bilen bilelikde dürli ýaşdaky dynç alýanlaryň we syýahatçylaryň ýokary isleglerini kanagatlandyrmak maksady bilen gurlan beýleki desgalar hem girýär. Bu ajaýyp desga gyşky we tomusky akwaparky, söwda merkezi, harytlaryň giň görnüşlerini hödürleýän onlarça dükanlary we supermarketi, kafeleri we restoranlary, amfiteatry, myhmanhanany, şeýle-de emeli daglary, kölleri, suw şaglawuklaryny, dag çeşmejiklerini öz içinde jemleýär.
                            «Awaza» milli syýahatçylyk zolagynda halkara ülňülerine laýyk gelýän ýokary derejeli myhmanhanalaryň, dynç alyş toplumlaryň, durmuş maksatly beýleki wajyp desgalaryň onlarçasynyň taslamalary amala aşyryldy. Bu ýerde ulag hyzmatlarynyň hili hem örän ýokary derejededir.
                            Türkmenbaşy şäherinde gurlan halkara howa menzili «Awazanyň» howa derwezesi bolup hyzmat edýär. Ýolagçylar uçardan howa menziliniň binasyna we yzyna teleskopik trap-geçelge arkaly geçýärler. Howa menziliniň halkara derejesini döwrebap inžener-tehniki enjamlar hem-de täze uçuş-gonuş zolagy üpjün edýär hem-de häzirki zaman ölçegler esasynda oňa ähli görnüşdäki howa ulaglara hyzmat etmek mümkinçiligi berilýär.
                            Türkmenbaşydaky täze deňiz porty bolsa, «PricewaterhouseCoopers» halkara konsalting kompaniýasynyň we Germaniýnyň «Hamburger Hafen und Logistik AG» ulag-logistika kompaniýasynyň sylaglary hem-de Gamburgyň we Gollandiýanyň portlarynyň konteýner terminallaryny dolandyryjy «Zeeland Seaports» kompaniýasynyň minnetdarlyk haty bilen sylaglandy. Şeýle hem port deňiz derejesinden pesde ýerleşýän iň uly port hökmünde Ginnesiň Bütündünýä rekordlar kitabyna girizildi. Şu kategoriýada dünýä Rekordlar kitaby «deňiz derejesinden pesde ýerleşýän iň uly emeli ada» diýip port gurlanda göçýän guşlary goramak maksady bilen gurlan emeli guşlar adasyny belledi.
                            «Awazanyň» ulag-logistika infrastrukturasyny ösdürmek boýunça işler amala aşyrylýar. Deňiz menzili kämilleşdirilýär, täze teplohodlar, ýahtalar we beýleki gämiler bilen flotuň üsti ýetirilýär. Türkmenbaşy şäheri Ýewropa bilen Günorta Aziýa döwletlerini gysga ýol boýunça birleşdirmek üçin gurulýan Demirgazyk-Günorta halkara ulag geçelgesiniň demir ýol merkezine öwrüler.
                            Kuwwatly gaz turbinaly elektrik stansiýanyň, deňiz suwuny süýjediji we arassalaýjy desgalaryň gurulmagy, agyz-suw ulgamyny çekmek boýunça işleriň ýerine ýetirilmegi inžener-tehniki infrastrukturanyň üstüni ýetirip, halkara deňiz dynç alyş zolagynyň kadaly hereket etmegini üpjün edýär. Kuwwaty 254 MWt bolan häzirki zaman elektrostansiýa «Awazany» yzygiderli elektroenergiýa bilen üpjün edip, ýurduň bitewi energoulgamyna girýär. 35 müň kub metr deňiz suwuny süýjediji desga bolsa, gije-gündiziň dowamynda syýahatçylyk zolagynda ýerleşýän myhmanhanalary hem-de gök zolaklary suw bilen üpjün edýär. Ol kenarýakada gurlup, täze döwrebap tehniki enjamlar we beýleki ähli zerur bolan inženerçilik tehniki serişdeler bilen üpjün edilen.
                            Uzynlygy 7 kilometr, ini 50-den 70 metre we çuňlugy 4 metre ýetýän «Awaza» derýasy syýahatçylyk zolagynyň iň iri we özboluşly desgalarynyň biri boldy. Derýanyň abadanlaşdyrylan iki kenarynda 28 sany jemgyýetçilik iýmit desgalary (bufetler, kafeler, gämi duralgaly açyk görnüşli restoranlar) ýerleşýär. Derýada kiçi göwrümli gämiler we gezelenç katerleri hereket edýär. Derýanyň üstünde gurnalan köpsanly ajaýyp köprüleriň her biri özüniň özboluşly bezeg nagyşlary bilen tapawutlanýarlar.
                            «Awaza» milli syýahatçylyk zolagynda 70-den gowrak dürli görnüşli desgalar, şol sanda, sport desgalar toplumyna girýän tennis meýdançalary, basketbol, woleýbol we mini-futbol üçin meýdançalar guruldy. Bu ýerde suw sport ýaryşlaryny geçirmek üçin ähli şertler göz öňünde tutulan. Derýanyň iki kenarýakasynda pyýadalar we welosiped sürüjiler üçin ýörite ýodalar geçirilen. Dynç alýanlar üçin derýa boýunça gyzykly gämi gezelençleri hödürlenýär.
                            Syýahatçylyk zolagynyň aglaba bölegini dynç alyş seýilgähleri we seýilbaglar tutýar. Has amatly howa şertlerini döretmek maksady bilen, gelejekde seýilgäh zolaklaryny giňeltmek we ösdürmek boýunça işler alnyp barylýar. Bu ýerde dünýäniň ähli künjeginiň botaniki baglaryndan getirilen üýtgeşik ösümlikler ýygnalyp, suw çüwdürimli seýilgähler dürlüligi hem-de gözelligi bilen tapawutlanýar. Seýilgähli zolaklary gülleýän baglyga öwürmek boýunça gündelik işler alnyp barylýar.
                            «Awaza» milli syýahatçylyk zolagy halkara biznes-forumlaryň, konferensiýalaryň, duşuşyklaryň, halkara festiwallaryň, bäsleşikleriň, konsertleriň, sport çäreleriniň geçirilýän ýerlerine öwrüldi. Syýahatçylyk zolagynda döwrebap Kongressler merkezi ulanmaga berildi we onda halkara forumlar, duşuşyklar ýokary derejede guramaçylykly geçirilýär.
                            Bulardan başga-da, dünýä ülňülerine laýyk gelýän sport toplumy ulanmaga tabşyryldy. Ýahtalar, gaýyklar, katerler, katamaranlar, suw paraşýutlary we ş.m. dynç alýanlar üçin hödürlenýän hyzmatlaryň diňe bir bölegi. Sport toplumlary, tennis meýdançalary, suw howuzlary, atlaryň üstünde gezelenç, attraksionlar, diskoklublar, restoranlar, kafeler mawy deňiz, gülleýän ýaýla hem-de depeler bilen bilelikde utgaşyp, aýratyn bir özboluşlulygy hem-de gözelligi döredýär.
                            «Awaza» milli syýahatçylyk zolagy özünde dünýäniň ösen, öňdebaryjy binagärlik hem-de inžener-tehniki çözgütlerini jemleýär. Innowasiýanyň häzirki zaman pikirleriniň we özara peýdaly hyzmatdaşlygyň merkezi bolup durýan bu özboluşly taslamany ösdürmek üçin Türkmenistanda uly mümkinçilikler döredilýär. «Awazanyň» infrastrukturasy ösýär we özgerýär. Syýahatçylyk zolagynyň özüne çekijiligini has-da artdyrmak boýunça geçirilýän ähli çäreler syýahatçylaryň artmagyna ýardam edýär.
                            «Awazada» amala aşyrylýan özgertmeler Türkmenistanyň diňe bir ykdysady taýdan güýçli depginde ösýändiginiň subutnamasy bolmak bilen çäklenmän, halkara derejesinde daşary ýurtlar tarapyndan ygtybarly synagdan geçen hyzmatdaş hökmünde ykrar edilendigini aýdyň görkezýär. Bu ýerde syýahatçylyk industriýasynyň döredilmegi durmuş meselelerini çözmekde, goşmaça iş orunlarynyň döredilmeginde, ykdysady taýdan ilatyň iş bilen meşgul bolmagyny ösdürmekde we ilatyň hal-ýagdaýynyň ýokarlanmagynda uly ähmiýete eýedir.
                            Türkmen halkynyň däp bolan myhmansöýüjilik ýörelgeleri hem-de ýurduň ilata hyzmat ediş pudagynyň ýokary derejesi, sebitiň ajaýyp howa hem-de şypaly ekologik şertleri, arassa deňiz suwy «Awaza» milli syýahatçylyk zolagynyň özboluşlylygyna aýratyn öwüşgin berýär.',

            'content_ru' => 'Развитие на туркменском берегу Каспия санаторно-курортного и экологического туризма имеет огромные перспективы. В настоящее время туризм, являясь одним из важных направлений экономики Туркменистана, содействует дальнейшему социально-экономическому развитию страны.
                            Сама природа позаботилась об этом уголке, одарив его приятными климатическими условиями, минеральными грязевыми источниками и многокилометровыми золотисто-песчаными морскими берегами, удивительными морскими пейзажами, биологическим многообразием Каспийского государственного заповедника, в том числе, многообразием птиц.
                            Презентация Национальной туристической зоны «Аваза», состоявшаяся в июне 2007 года, стала большим событием мирового значения, а также ярким свидетельством нового подхода к развитию огромного потенциала индустрии отдыха и туризма в нашей стране. Цель реализации этого важного проекта, с точки зрения социальной политики Туркменистана, заключается в обеспечении населения страны всеми необходимыми условиями жизни и отдыха. В этой связи, большое значение имеет наличие в регионе разветвлённой транспортно-коммуникационной инфраструктуры, в т.ч., международного морского порта и аэропорта, автомобильных и железных дорог.
                            Для претворения в жизнь проекта Национальной туристической зоны «Аваза» была выделена территория общей площадью 5000 гектаров. В конце 2007 года началось строительство первых объектов туристической зоны. В июне 2009 года на берегу Каспийского моря состоялась церемония открытия новых объектов Национальной туристической зоны «Аваза».
                            «Аваза» занимает особое место в стратегических планах государственной политики Туркменистана на ближайшие десятилетия. Этот проект аккумулирует и сочетает в себе творческие решения с национальным колоритом с передовыми достижениями мировой архитектурно-строительной и инженерно-технической мысли.
                            В настоящее время в Национальной туристической зоне «Аваза» действуют 18 гостиниц, одновременно принимающих более 10 тысяч отдыхающих, 8 санаторно-курортных центров, в т.ч., детские центры отдыха на 1380 мест, 9 коттеджных комплексов. К услугам отдыхающих работают 4 парка отдыха, два из них – парки с игровыми аттракционами. Парки отдыха с театрализованными интерактивными морскими фонтанами, амфитеатором, детскими площадками с аттракционами, многочисленными кафе и ресторанами, зелёными зонами и техническими объектами общей площадью 83600 кв. метров стали излюбленным местом жителей и гостей города.
                            Уникальный комплекс фонтанов высотой от 40 до 100 метров построен с применением современных технологических решений. На экранах из фонтанов размером 24 метра в длину и 60 метров в ширину, расположенных в 85 метрах от морского берега, в сочетании с музыкальным сопровождением демонстрируются различные голографические изображения, доходящие до 20 метров в высоту. Через 50 метров по дорожке к берегу простираются две тропинки по 34 метра в разные стороны, ведущие к смотровой площадке. Отсюда можно наблюдать за красивым морским пейзажем и удивительными изображениями на фонтанных экранах.
                            В июле 2018 года был сдан в эксплуатацию аквапарк общей площадью 30 гектаров. Аквапарк состоит из водных аттракционов и других объектов, предназначенных для отдыхающих всех возрастов. В комплекс входят зимний и летний аквапарки, торговый центр, десятки магазитов и супермаркет, кафе и рестораны, амфитеатр, гостиница, искусственные горы и озёра, водные каскады и горные источники.
                            В Национальной туристической зоне «Аваза», в соответствии с международными стандартами, осуществлено строительство десятков гостиниц, комплексов для отдыха, других объектов социального назначения. Здесь также на высоком уровне предоставляются услуги сферы транспорта.
                             
                            Международный аэропорт, построенный в городе Туркменбаши, служит воздушными воротами «Авазы». Путь от самолёта до здания аэровокзала оснащен телескопическим трапом. Международный уровень аэропорта обеспечивается также за счёт оснащения современным инженерно-техническим оборудованием и новой взлетно-посадочной полосой. В соответствии с мировыми стандартами, здесь есть возможности для оказания услуг всем видам воздушного транспорта.
                            Новый международный морской порт в Туркменбаши был отмечен наградой международной консалтинговой компании «PricewaterhouseCoopers» и немецкой транспортно-логистической компании «Hamburger Hafen und Logistik AG», сертификатом от управляющей контейнерными терминалами в порту Гамбурга и портов Голландии «Zeeland Seaports». Также порт внесён во Всемирную книгу рекордов Гиннеса как самый большой порт ниже уровня моря. Сборник мировых рекордов отметил как «самый большой искусственный остров ниже уровня моря» искусственный птичий остров, сооружённый при строительстве порта в целях охраны орнитофауны.
                            Проводятся работы по развитию транспортно-логиcтической инфраструктуры «Авазы». Совершествуется морской вокзал, флот расширяется за счёт новых теплоходов, яхт и других пароходов. Город Туркменбаши станет одним из самых крупных транспортных центров железной дороги международного транспортного коридора «Север-Юг», призванный по кратчайшему маршруту связать государства Европы и Южной Азии.
                            Мощная газотурбинная электростанция, строительство водоопреснительных и водоочистительных сооружений, проведение сети питьевой воды, расширив инженерно-техническую инфраструктуру, обеспечивает нормальную работу морской зоны отдыха. Современная электростанция мощностью 254 MWt, обеспечивающая полностью электроэнергией «Авазу», входит в единую энергосеть страны. Водоопреснительная станция на 35 тысяч кубических метров воды круглосуточно обеспечивает водой гостиницы и зелёные зоны, расположенные на территории «Авазы». Постороенная в прибрежной зоне станция оснащена новым современным техническим оборудованием и всеми необходимыми инженерно-техническими устройствами.
                            Река «Аваза» длиной 7 километров, шириной от 50 до 70 метров и глубиной 4 метра является самым крупным и уникальным объектом туристической зоны. На обустроенных двух берегах реки расположены 28 объектов общественного питания (буфеты, кафе, открытые рестораны с пристанями для кораблей). По реке курсируют маленькие пароходы и круизные катера; многочисленные красивые мосты, возведённые над рекой, отличаются своеобразными узорами.
                            В Национальной туристической зоне «Аваза» построено более 70-ти различных сооружений, в т.ч., теннисные, баскетбольные, волейбольные площадки и поля для мини-футбола, входящие в комплекс спортивных объектов. Здесь предусмотрены все условия для проведения спортивных соревнований по плаванию. На обоих берегах реки оборудованы пешеходные и велосипедные тропы. К услугам отдыхающих предлагаются интересные морские круизы.
                            Большую часть туристической зоны занимают парки и скверы. С целью создания наиболее комфортных климатических условий, в будущем парковые зоны предполагается расширить и развить. Здесь собраны удивительные растения, привезённые из ботанических садов со всех уголков мира. Парки и  скверы с фонтанами отличаются многообразием и красотой. Ведутся ежедневные работы по превращению парковых зон в цветущие сады.
                            Национальная туристическая зона «Аваза» превратилась в место проведения международных бизнес-форумов, конференций, встреч, международных фестивалей, соревнований, спортивных мероприятий. В туристической зоне сдан в эксплуатацию современный Конгресс-центр, в котором на высоком организационном уровне проходят международные форумы и встречи.
                            Кроме этого, сдан спортивный комплекс, соответствующий мировым стандартам. Яхты, лодки, катера, катамараны, водные парашюты и др. – только небольшая часть услуг, предлагаемых для отдыхающих. Спортивные комплексы, теннисные корты, водные бассейны, прогулки на лошадях, аттракционы, дискоклубы, рестораны, кафе в гармонии с бирюзовым морем, цветущими полями и горными вершинами создают уникальную и прекрасную атмосферу отдыха.
                            Национальная туристическая зона «Аваза» воплощает в себе передовые мировые архитектурно-строительные и инженерно-технические решения. В Туркменистане создаются большие возможности для развития этого проекта, являющегося центром инновационных решений и взаимовыгодного сотрудничества. Развивается и преображается инфраструктура «Авазы». Последовательно реализуются меры для дальнейшего роста привлекательности туристической зоны.
                            Преобразования, осуществляющиеся в «Авазе», являются не только свидетельством быстрого роста экономики страны, но и ярко демонстрируют международное признание Туркменистана в качестве надёжного и испытанного временем партнёра. Создание здесь туристической индустрии имеет большое значение и с точки зрения решения социальных задач, связанных с обеспечением благополучия населения.
                            Традиции и обычаи гостеприимства туркменского народа, высокий уровень сферы услуг в стране, комфортный климат и благоприятные экологические условия, чистая морская вода создают особую атмосферу притягательности Национальной туристической зоне «Аваза».
                            ',

            'content_en' => 'Hazaryň türkmen böleginde sagaldyş-dynç alyş we ekologiki syýahatçylygy ösdürmeklik ägirt uly mümkinçiliklere eýe bolýar. Häzirki wagtda syýahatçylyk Türkmenistanyň ykdysadyýetiň wajyp ugurlarynyň biri bolmak bilen, ýurduň durmuş-ykdysady taýdan mundan beýläk hem ösmegine ýardam edýär.
                            Tebigatyň özi bu künjek hakynda alada edip, mylaýym howa şertleri, minerally palçyk çeşmeleri we köp kilometrlere uzap gidýän altyn öwüşginli-çägesöw deňiz kenarlary, gözelligi boýunça täsin deňiz görnüşleri, Hazar döwlet goraghanasynyň biologik köpdürliligi bilen tapawutlanýan, şol sanda, suw-batgalyk ýerlerdäki guşlaryň köpdürliligi bilen eçilipdir.
                            2007-nji ýylyň iýun aýynda geçirilen «Awaza» milli syýahatçylyk zolagynyň tanyşdyrylyş dabarasy dünýä möçberinde uly waka boldy hem-de ýurdumyzyň dynç alyş we syýahçylyk industriýasyny ösdürmek boýunça täzeçe çemeleşmäniň aýdyň subutnamasyna öwrüldi. Bu ähmiýetli taslamanyň esasy maksady - Türkmenistanyň durmuş syýasatynyň nukdaýnazaryndan şeýle wajyp taslamany hemmetaraplaýyn amala aşyryp, ýurduň ilatynyň ýaşaýşy üçin zerur bolan şertler bilen doly üpjün etmekden ybarat bolup durýar. Şunuň bilen baglylykda, bu sebitde ulag-aragatnaşyk ulgamynyň, şol sanda, halkara deňiz portunyň we howa menziliniň, awtoulag hem-de demir ýollarynyň barlygy örän ähmiýetlidir.
                            «Awaza» milli syýahatçylyk zolagynyň taslamasyny durmuşa geçirmek üçin umumy meýdany 5000 gektar bolan ýer bölegi bölünip berildi. 2007-nji ýylyň ahyrynda bu syýahatçylyk zolagyň ilkinji desgalarynyň gurluşyklaryna başlanyldy. 2009-njy ýylyň iýunynda Hazar deňziniň kenarynda «Awaza» milli syýahatçylyk zolagynda täze binalaryň açylyş dabarasy boldy.
                            «Awaza» Türkmenistanyň döwlet syýasatynda geljekki onýyllyklar üçin ýurduň strategiki meýilnamasynda aýratyn orny tutýar. Bu taslama milli öwüşgünli döredijilik çözgütleri bilen birlikde dünýä arhitekturasynyň we binagärliginiň, şeýle hem inžener-tehniki pikirleriniň iň öňdebaryjy üstünliklerini utgaşykly amala aşyrmaga ýardam edýär.
                            Häzirki wagtda «Awaza» milli syýahatçylyk zolagynda bir wagtyň özünde dynç alýanlaryň 10 müňden gowragyny kabul edip bilýän 18 sany myhmanhana, 8 sany dynç alyş we sagaldyş merkezleri, şol sanda, 1380 orunlyk çagalar dync alyş merkezler hem-de 9 sany kottejler toplumlary işleýär. Dynç alýanlaryň hyzmatynda 4 sany seýilgäh bolup, olardan 2-si oýun attraksionly seýilgählerdir. Umumy meýdany 83600 inedördül metr bolan teatrlaşdyrylan intraktiw deňiz suw çüwdürümlerini, amfiteatry, çagalar üçin attraksionly oýun meýdançalary, köpsanly kafeleri we restoranlary, gök zolaklary, tehniki desgalary öz içine alýan seýilgähler bu ýerde dynç alýanlaryň hem-de şäheriň ilatynyň iň söýgüli ýerlerine öwrüldi.
                            Beýikligi 40-dan 100 metre çenli bolan suw çüwdürümler toplumy häzirki zaman ýokary tehnologiýalar esasynda sazlaşykly gurlan desgalar hökmünde aýratyn özboluşlylygy bilen tapawutlanýarlar. Deňiz kenaryndan 85 metr daşlykda ýerleşýän boýy 24 metr, ini 60 metr bolan suw çüwdürimleriniň ýüzündäki ekranda dürli görnüşli golografik şekiller we tans edýän sudurlar görünýär we olar seýilgähde goýberilýän saz owazy bilen utgaşykly hereket edip yzygiderli çalyşyp durýar. Deňiz suw çüwdürümlerinden ybarat bolan ekranda görünýän golografik şekilleriň boýy 20 metre ýetip, şekilleri hakyky ýaly edip görkezýär. Deňze tarap gurnalan ýodajyk arkaly 50 metr aralygy geçip, iki tarapa uzap gidýän her tarapynyň uzynlygy 34 metr bolan ýodajykdaky gözegçilik meýdançasyndan gündiz Hazar deňziniň gözelligini, agşamara bolsa ýakyn aralykdaky deňiz suw çüwdürümleriniň hereketlerini synlamak bolýar.
                            2018-nji ýylyň iýulynda umumy meýdany 30 gektar bolan akwapark ulanylyşa berildi. Akwaparkyň düzümine suw attraksionlary bilen bilelikde dürli ýaşdaky dynç alýanlaryň we syýahatçylaryň ýokary isleglerini kanagatlandyrmak maksady bilen gurlan beýleki desgalar hem girýär. Bu ajaýyp desga gyşky we tomusky akwaparky, söwda merkezi, harytlaryň giň görnüşlerini hödürleýän onlarça dükanlary we supermarketi, kafeleri we restoranlary, amfiteatry, myhmanhanany, şeýle-de emeli daglary, kölleri, suw şaglawuklaryny, dag çeşmejiklerini öz içinde jemleýär.
                            «Awaza» milli syýahatçylyk zolagynda halkara ülňülerine laýyk gelýän ýokary derejeli myhmanhanalaryň, dynç alyş toplumlaryň, durmuş maksatly beýleki wajyp desgalaryň onlarçasynyň taslamalary amala aşyryldy. Bu ýerde ulag hyzmatlarynyň hili hem örän ýokary derejededir.
                            Türkmenbaşy şäherinde gurlan halkara howa menzili «Awazanyň» howa derwezesi bolup hyzmat edýär. Ýolagçylar uçardan howa menziliniň binasyna we yzyna teleskopik trap-geçelge arkaly geçýärler. Howa menziliniň halkara derejesini döwrebap inžener-tehniki enjamlar hem-de täze uçuş-gonuş zolagy üpjün edýär hem-de häzirki zaman ölçegler esasynda oňa ähli görnüşdäki howa ulaglara hyzmat etmek mümkinçiligi berilýär.
                            Türkmenbaşydaky täze deňiz porty bolsa, «PricewaterhouseCoopers» halkara konsalting kompaniýasynyň we Germaniýnyň «Hamburger Hafen und Logistik AG» ulag-logistika kompaniýasynyň sylaglary hem-de Gamburgyň we Gollandiýanyň portlarynyň konteýner terminallaryny dolandyryjy «Zeeland Seaports» kompaniýasynyň minnetdarlyk haty bilen sylaglandy. Şeýle hem port deňiz derejesinden pesde ýerleşýän iň uly port hökmünde Ginnesiň Bütündünýä rekordlar kitabyna girizildi. Şu kategoriýada dünýä Rekordlar kitaby «deňiz derejesinden pesde ýerleşýän iň uly emeli ada» diýip port gurlanda göçýän guşlary goramak maksady bilen gurlan emeli guşlar adasyny belledi.
                            «Awazanyň» ulag-logistika infrastrukturasyny ösdürmek boýunça işler amala aşyrylýar. Deňiz menzili kämilleşdirilýär, täze teplohodlar, ýahtalar we beýleki gämiler bilen flotuň üsti ýetirilýär. Türkmenbaşy şäheri Ýewropa bilen Günorta Aziýa döwletlerini gysga ýol boýunça birleşdirmek üçin gurulýan Demirgazyk-Günorta halkara ulag geçelgesiniň demir ýol merkezine öwrüler.
                            Kuwwatly gaz turbinaly elektrik stansiýanyň, deňiz suwuny süýjediji we arassalaýjy desgalaryň gurulmagy, agyz-suw ulgamyny çekmek boýunça işleriň ýerine ýetirilmegi inžener-tehniki infrastrukturanyň üstüni ýetirip, halkara deňiz dynç alyş zolagynyň kadaly hereket etmegini üpjün edýär. Kuwwaty 254 MWt bolan häzirki zaman elektrostansiýa «Awazany» yzygiderli elektroenergiýa bilen üpjün edip, ýurduň bitewi energoulgamyna girýär. 35 müň kub metr deňiz suwuny süýjediji desga bolsa, gije-gündiziň dowamynda syýahatçylyk zolagynda ýerleşýän myhmanhanalary hem-de gök zolaklary suw bilen üpjün edýär. Ol kenarýakada gurlup, täze döwrebap tehniki enjamlar we beýleki ähli zerur bolan inženerçilik tehniki serişdeler bilen üpjün edilen.
                            Uzynlygy 7 kilometr, ini 50-den 70 metre we çuňlugy 4 metre ýetýän «Awaza» derýasy syýahatçylyk zolagynyň iň iri we özboluşly desgalarynyň biri boldy. Derýanyň abadanlaşdyrylan iki kenarynda 28 sany jemgyýetçilik iýmit desgalary (bufetler, kafeler, gämi duralgaly açyk görnüşli restoranlar) ýerleşýär. Derýada kiçi göwrümli gämiler we gezelenç katerleri hereket edýär. Derýanyň üstünde gurnalan köpsanly ajaýyp köprüleriň her biri özüniň özboluşly bezeg nagyşlary bilen tapawutlanýarlar.
                            «Awaza» milli syýahatçylyk zolagynda 70-den gowrak dürli görnüşli desgalar, şol sanda, sport desgalar toplumyna girýän tennis meýdançalary, basketbol, woleýbol we mini-futbol üçin meýdançalar guruldy. Bu ýerde suw sport ýaryşlaryny geçirmek üçin ähli şertler göz öňünde tutulan. Derýanyň iki kenarýakasynda pyýadalar we welosiped sürüjiler üçin ýörite ýodalar geçirilen. Dynç alýanlar üçin derýa boýunça gyzykly gämi gezelençleri hödürlenýär.
                            Syýahatçylyk zolagynyň aglaba bölegini dynç alyş seýilgähleri we seýilbaglar tutýar. Has amatly howa şertlerini döretmek maksady bilen, gelejekde seýilgäh zolaklaryny giňeltmek we ösdürmek boýunça işler alnyp barylýar. Bu ýerde dünýäniň ähli künjeginiň botaniki baglaryndan getirilen üýtgeşik ösümlikler ýygnalyp, suw çüwdürimli seýilgähler dürlüligi hem-de gözelligi bilen tapawutlanýar. Seýilgähli zolaklary gülleýän baglyga öwürmek boýunça gündelik işler alnyp barylýar.
                            «Awaza» milli syýahatçylyk zolagy halkara biznes-forumlaryň, konferensiýalaryň, duşuşyklaryň, halkara festiwallaryň, bäsleşikleriň, konsertleriň, sport çäreleriniň geçirilýän ýerlerine öwrüldi. Syýahatçylyk zolagynda döwrebap Kongressler merkezi ulanmaga berildi we onda halkara forumlar, duşuşyklar ýokary derejede guramaçylykly geçirilýär.
                            Bulardan başga-da, dünýä ülňülerine laýyk gelýän sport toplumy ulanmaga tabşyryldy. Ýahtalar, gaýyklar, katerler, katamaranlar, suw paraşýutlary we ş.m. dynç alýanlar üçin hödürlenýän hyzmatlaryň diňe bir bölegi. Sport toplumlary, tennis meýdançalary, suw howuzlary, atlaryň üstünde gezelenç, attraksionlar, diskoklublar, restoranlar, kafeler mawy deňiz, gülleýän ýaýla hem-de depeler bilen bilelikde utgaşyp, aýratyn bir özboluşlulygy hem-de gözelligi döredýär.
                            «Awaza» milli syýahatçylyk zolagy özünde dünýäniň ösen, öňdebaryjy binagärlik hem-de inžener-tehniki çözgütlerini jemleýär. Innowasiýanyň häzirki zaman pikirleriniň we özara peýdaly hyzmatdaşlygyň merkezi bolup durýan bu özboluşly taslamany ösdürmek üçin Türkmenistanda uly mümkinçilikler döredilýär. «Awazanyň» infrastrukturasy ösýär we özgerýär. Syýahatçylyk zolagynyň özüne çekijiligini has-da artdyrmak boýunça geçirilýän ähli çäreler syýahatçylaryň artmagyna ýardam edýär.
                            «Awazada» amala aşyrylýan özgertmeler Türkmenistanyň diňe bir ykdysady taýdan güýçli depginde ösýändiginiň subutnamasy bolmak bilen çäklenmän, halkara derejesinde daşary ýurtlar tarapyndan ygtybarly synagdan geçen hyzmatdaş hökmünde ykrar edilendigini aýdyň görkezýär. Bu ýerde syýahatçylyk industriýasynyň döredilmegi durmuş meselelerini çözmekde, goşmaça iş orunlarynyň döredilmeginde, ykdysady taýdan ilatyň iş bilen meşgul bolmagyny ösdürmekde we ilatyň hal-ýagdaýynyň ýokarlanmagynda uly ähmiýete eýedir.
                            Türkmen halkynyň däp bolan myhmansöýüjilik ýörelgeleri hem-de ýurduň ilata hyzmat ediş pudagynyň ýokary derejesi, sebitiň ajaýyp howa hem-de şypaly ekologik şertleri, arassa deňiz suwy «Awaza» milli syýahatçylyk zolagynyň özboluşlylygyna aýratyn öwüşgin berýär.
                            ',
        ]);
    }
}
