<?php

namespace Database\Seeders;

use App\Models\TkmEconomy;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TkmEconomySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        TkmEconomy::create([
            'title_tm' => 'YKDYSADYÝET',
            'title_ru' => 'ЭКОНОМИКА',
            'title_en' => 'ECONOMY',
            
            'content_tm' => '«Berkarar döwletiň täze eýýamynyň Galkynyşy: Türkmenistany 2022-2052-nji ýyllarda durmuş-ykdysady taýdan ösdürmegiň Milli maksatnamasynyň» we «Türkmenistanyň Prezidentiniň ýurdumyzy 2022-2028-nji ýyllarda durmuş-ykdysady taýdan ösdürmek boýunça maksatnamasynyň» wezipelerine laýyklykda, Türkmenistanyň bitaraplyk syýasaty ählumumy strategik möhüm gural hökmünde dünýä we sebit döwletleri, şeýle hem abraýly halkara guramalary bilen hyzmatdaşlygy mundan beýläk-de ösdürmäge gönükdirilendir. Döwletiň milli ykdysadyýetiniň diwersifikasiýa ýoly bilen alnyp barylmagy we ulgamda ýokary tehnologiýalaryň we sanlylaşdyrma prosessleriniň ýaýbaňlandyrylmagy global ykdysady giňişligine we umumydünýä hojalyk gatnaşyklaryna işjeň goşuluşmagyna güýçli itergi berýär.
                            Türkmenistan milli ykdysadyýetiniň çalt depginler bilen ösýän şertlerinde dünýäniň dürli döwletleri bilen ýokary tehnologiýaly pudaklarda hyzmatdaşlyk etmäge, häzirki zamanyň öňdebaryjy bilimlerini we dolandyryş çözgütlerini ornaşdyrmaga uly ähmiýet berýär. «Türkmenistanyň 2020-2025-nji ýyllar üçin daşary ykdysady işiniň ösüşiniň maksatnamasyny», «Türkmenistanyň 2021-2030-njy ýyllar üçin daşary söwda strategiýasyny» we söwda, ykdysadyýet hem-de maýa goýumlar ulgamlaryna degişli resminamalardan gelip çykýan çäreleri hem-de taslamalary amala aşyrmak boýunça degişli işler alnyp barylýar. Bu babatda, milli ykdysadyýetiň durnukly ösüşine we ilatynyň durmuş derejesiniň ýokarlandyrylmagyna ýardam berýän oňyn halkara şertleri döretmek, dünýäniň hojalyk gatnaşyklaryna işjeň gatnaşmak, daşary ykdysady hyzmatdaşlygy has-da ösdürmek, iri maýa goýumlaryny ýurdumyza çekmek ýaly wajyp wezipeler ileri tutulýar.
                            Türkmenistanyň Prezidenti Serdar Berdimuhamedowyň 2022-nji ýylyň 23-nji sentýabrynda Döwlet maslahatynda eden çykyşynda belleýşi ýaly, 2022-2028-nji ýyllarda Döwlet býujetiniň serişdeleri durmuş-ykdysady ösüş strategiýany durmuşa geçirmegiň esasy ugurlaryna, ykdysadyýetiň innowasion ösüşini üpjün etmäge gönükdiriler. Býujetiň agramly böleginiň, ozalkylary ýaly, durmuş ulgamyny maliýeleşdirmek üçin sarp ediljekdigi nygtaldy.
                            «Geljek ýedi ýylda 278,9 milliard manatdan gowrak maýa goýumlaryny özleşdirip, ýurdumyzyň önümçilik kuwwatyny has-da pugtalandyrarys. Bu döwürde zähmet haklarynyň möçberlerini 1,8 esse artdyrarys. Ykdysadyýetimiziň ähli pudaklarynda 30 mü­ňe golaý goşmaça iş orunlaryny dörederis. Adam başyna düşýän ýaşaýyş jaýlarynyň umumy meýdanyny 102,2 göterim artdyrarys. Mekdebe çenli çagalar edaralarynyň 40-syny, orta mekdepleriň 54-sini, täze 4 sany ýokary hünär bilim edarasyny, 10 sany döwrebap hassahanany, 7 sany medeniýet öýüni, şol sanda 500-den gowrak täze önümçilik we durmuş maksatly binalardyr desgalary gurarys. Bu işleriň ählisi Gahryman Arkadagymyzyň «Döwlet adam üçindir!» diýen şygarynyň dowamy bolan «Watan di­ňe halky bilen Watandyr! Döwlet di­ňe halky bilen döwletdir!» diýen baş ýörelgämize laýyklykda, ilkinji nobatda, mähriban halkymyzyň abadançylygynyň ýokarlandyrylmagyna, ýurdumyzyň kuwwatynyň has-da artdyrylmagyna gönükdirilendir», - diýip, Türkmenistanyň Prezidenti belledi.
                            Orta we uzakmöhletleýin döwlet maksatnamalarynyň kabul edilmegi bilen, Türkmenistanda ösen elektroenergetika, nebit we gaz çykarýan, nebiti gaýtadan işleýän, himiýa we nebit-himiýa senagatlary, maşyn-gurluşyk we demiri gaýtadan işleýän, gurluşyk materiallaryny öndürýän desgalar, ýeňil we azyk senagatynyň kärhanalary bilen üpjün edilen köp pudakly dürli maksatly ykdysadyýet döredildi.
                            Ylmyň we tehnikanyň öň­debaryjy gazananlaryny, iň gowy dünýä tejribelerini ornaşdyrmak arkaly obasenagat toplumyny ösdürmekde we azyk bolçulygyny üpjün etmekde ýokary netijeler gazanylýar. Oba milli maksatnamasyna laýyklykda, ak bugdaýyň mekany bolan Türkmenistanda 2022-nji ýylda döwlet harmanyna 1 million 500 müň tonna golaý bugdaý tabşyryldy. Dokma kärhanalarynyň 60-dan gowragynda nah we garyşyk ýüplükleriň dürli görnüşleri, matalar, taýýar egin-eşikler, el halylary öndürilip, dünýä bazaryna ýokary hilli harytlar çykarylýar. Türkmenistan bu gün bäsdeşlige ukyply smart telewizorlary, noutbuklary, planşetleri, monobloklary, sensor ekranly kompýuterleri hem dünýä bazaryna ugradýar.
                            2022-nji ýylyň alty aýynyň makroykdysady görkezijileri boýunça Türkmenistanyň ykdysadyýetiniň geçen ýylyň alty aýynyň netijeleri bilen deňeşdirilende, ähli ugurlar boýunça ösüşe eýe bolandygyny, hemme pudaklaryň we sebitleriň durnukly ösüşini üpjün etmäge gönükdirilen toplumlaýyn çäreleriň amala aşyrylandygyny görkezýär. Jemi içerki önüm 6 göterim ýokarlandy. 2021-nji ýylyň degişli döwri bilen deňeşdirilende, jemi öndürilen önüm 11,5 göterim artdy. Şu ýylyň alty aýy boýunça bölek satuw haryt dolanyşygy 10,4 göterim, daşary söwda dolanyşygy bolsa, 40 göterim köpeldi. Ýurdumyzyň iri we orta kärhanalarynda ortaça aýlyk zähmet haky 10,4 göterim ýokarlandy.
                            Türkmenistanyň halkara ykdysady işiniň ileri tutulýan ugurlarynyň biri BMG-niň Ösüş maksatnamasyny durmuşa geçirmäge işjeň we netijeli gatnaşmaga gönükdirilendir. Ýurdumyzyň energetika we energiýa howpsuzlygy, durnukly ulag ulgamy, ekologiýa we daşky gurşawy goramak, hususan-da, wodorod energiýasy boýunça wajyp meseleleriň çözülmegi, azyk howpsuzlygy we beýleki ugurlar babatda halkara hyzmatdaşlyk has hem giňeldilýär.
                            Ýurdumyz dünýä döwletleriniň arasynda özüniň ýangyja we elektrik energiýasyna bolan isleglerini öz hususy baýlyklary bilen doly kanagatlandyrýar, şeýle hem onuň ep-esli bölegini daşary ýurtlara çykarýar. Türkmenistan milli we umumadamzat bähbitlerine özüniň ägirt uly energetika mümkinçiligini netijeli peýdalanmaga örän jogapkärli çemeleşmäge ygrarlylygyny bildirýär hem-de bu ugurda anyk wezipeleri ýerine ýetirýär. Tebigy gazyň gorlary boýunça dünýäde dördünji orny eýeleýän Türkmenistanyň energetika strategiýasynyň möhüm ugurlarynyň biri hem ony dünýä bazaryna ibermegi diwersifikasiýalaşdyrmakdan ybarat bolup durýar. BMG-niň Baş Assambleýasy tarapyndan energiýa serişdelerini ygtybarly we durnukly üstaşyr geçirmek baradaky Kararnamalarynyň kabul edilmegi hem muňa aýdyň subutnamadyr.
                            Daşary ýurtly hyzmatdaşlar bilen Hazaryň türkmen bölegindäki ýataklar özleşdirilýär. Türkmenistan-Owganystan-Pakistan-Hindistan gaz geçirijisiniň gurluşygy amala aşyrylýar. Bu täze energiýa köprüsi türkmen tebigy gazyny Günorta Aziýanyň iri ýurtlaryna uzak möhletleýin ugradylmagyny üpjün etmek bilen, tutuş sebitiň durmuş-ykdysady taýdan ösmegi, işewür hyzmatdaşlygyň, parahatçylygyň berkemegi üçin kuwwatly itergi bolup hyzmat eder.
                            Günden we ýelden elektrik energiýasyny öndürýän stansiýanyň, içerki energetika halkasynyň, Türkmenistan-Owganystan-Pakistan elektrik geçiriji ulgamynyň gurluşyklary dowam etdirilýär. Aşgabat şäherinde Energetika enjamlaryny abatlaýyş we hyzmat ediş merkeziniň açylmagy pudagy diwersifikasiýa ýoly bilen ösdürmek üçin şertleri döredýär.
                            Türkmenistanyň durmuşa geçirýän ulag-logistika strategiýasy öz gözbaşyny gadymyýetden - Beýik Ýüpek ýolundan alyp gaýdýar. Türkmenistan bu gün Demirgazyk-Günorta, Gündogar-Günbatar ugurlary boýunça üstaşyr ulag taslamalaryny amala aşyrýar. Türkmenistan-Azerbaýjan-Gruziýa-Türkiýe, Özbegistan-Türkmenistan-Eýran-Oman-Katar hem-de TRACEKA halkara ulag geçelgeleriniň döredilmegine işjeň gatnaşýar. Şeýle-de Amyderýanyň üstünden geçýän awtomobil we demir ýol köprülerini, Aşgabat, Türkmenbaşy, Türkmenabat, Kerki şäherlerinde Halkara howa menzillerini, Türkmenbaşy şäherinde Halkara de­ňiz portuny gurmak boýunça taslamalar amala aşyryldy.
                            Türkmenistan maýa goýumlar babatda hem özüne çekiji ýurtdur. Içerki we daşary ýurt maýa goýum işjeň­ligini artdyrmak, ýurduň sebitleriniň ykdysady kuwwatyny berkitmek hem-de durmuş-ykdysady taýdan durnukly ösüşini üpjün etmek babatda ägirt uly işler amala aşyrylýar. Döwletimiziň öňe sürýän amatly maýa goýum gurşawyny döretmek babatdaky başlangyçlaryna halkara reýtinglerde ýokary baha berilýär.
                            Türkmenistan anyk kesgitlenen ugurlar boýunça strategiki wezipelerden we maksatnamalaýyn resminamalardan ugur alýar we daşary ýurtlar, halkara we sebit ykdysady hem-de maliýe guramalary we institutlary bilen hemmetaraplaýyn özara bähbitli söwda-ykdysady gatnaşyklaryny dowam etmäge ygrarly we bu ugurda amala aşyrylmaly wezipeler boýunça tagallalary güýçlendirýär. Işjeň hyzmatdaşlygy alyp barmakda Ykdysady Hyzmatdaşlyk we Ösüş Guramasy, Halkara Pul Gaznasy, Bütindünýä Banky Topary, Ýewropanyň Täzeleniş we Ösüş Banky, Aziýa Ösüş Banky, Yslam Ösüş Banky we beýleki maliýe-ykdysady düzümler bilen gatnaşyklary pugtalandyrmak syýasatyny dowam edýär.
                            Soň­ky döwürde söwda we maliýe ugurlary boýunça forumlary, sergileri, ýarmarkalary, simpoziumlary, şol sanda, wirtual sergileri geçirmek bilen, ýurdumyzyň senagat we intellektual kuwwaty dünýä ýaýylýar. Dünýäniň iri ykdysady merkezlerinde geçirilen Bütindünýä «EKSPO» sergilerinde ýurdumyzyň ýeten derejesine ýokary baha berilýär. Halkara hyzmatdaşlygyň täze döwrebap gurallaryny we nusgalaryny ornaşdyrmak maksady bilen, Halkara sergiler býurosy bilen hyzmatdaşlygyň gerimini gi­ňeltmek boýunça çäreleri durmuşa geçirmek, daşary ýurtlarda guralýan sergilere we ýarmarkalara milli önümler, hyzmatlar, senagat nusgalar bilen gatnaşmagy işjeňleşdirmek ileri tutulýan wezipeleriň hatarynda durýar.
                            Türkmenistan energetika ulgamynda hem global we sebit derejelerinde giň hyzmatdaşlygyň pugtalandyrylmagy ugrunda Halkara Energetika Hartiýasy, Halkara Energetika agentligi, Atom energiýasy boýunca halkara agentligi, Energiýanyň gaýtadan dikeldilýän çeşmeleri boýunça halkara agentligi, şeýle hem energiýa serişdelerini öndüriji öňdebaryjy daşary ýurt kompaniýalary bilen hyzmatdaşlygy amala aşyrýar.
                            Türkmenistan sebit hem-de halkara ulag we maglumat-kommunikasiýa ulgamlaryna işjeň goşulmak ugrundaky işlerini dowam etmek bilen, özüniň halkara ulag-üstaşyr mümkinçiliklerini artdyrýar. Bütindünýä Söwda Guramasynyň agzalygyna girmek boýunça (häzirki wagtda «işjeň synçy» derejesinde) amala aşyrylýan hereketleriň çäklerinde hem-de erkin söwda boýunça halkara şertnamalara gatnaşýan ýurt hökmünde Türkmenistan söwda-ykdysady ugurly gyzyklanmalaryň ilerledilmegi babatynda işjeň syýasat alyp barýar. BMG-niň Halkara söwda hukugy boýunça komissiýasynyň 2022-2028-nji ýyllar döwri üçin agzasy hökmünde ýurdumyz onuň çäklerinde hem degişli işlere başlady.
                            Daşary ykdysady ulgamda alnyp barylýan tagallalar ýurdumyzyň dünýä hojalyk gatnaşyklaryndaky ornunyň pugtalandyrylmagyna, täze bazarlaryň özleşdirilmegine hem-de eksport mümkinçilikleriniň we daşary ýurt maýa goýumlarynyň artdyrylmagyna, türkmen harytlarynyň we hyzmatlarynyň dünýä bazaryna çykarylmagyna, halkara we sebit ykdysady hem-de maliýe guramalarynyň mümkinçilikleriniň doly göwrümde peýdalanylmagyna, şeýle-de dünýäniň ykdysady we maliýe bileleşikleriniň öňünde ýurdumyzyň oňyn abraýynyň kemala getirilmegine gönükdirilendir.
                            ',

            'content_ru' => 'В соответствии с задачами Программы «Возрождение новой эпохи могущественного государства: Национальная программа социально-экономического развития Туркменистана в 2022-2052 годах» и «Программы Президента Туркменистана по социально-экономическому развитию страны в 2022-2028 годах», нейтральная политика Туркменистана в качестве всеобщего стратегически важного инструмента, направлена на дальнейшее развитие сотрудничества с мировыми и региональными государствами, а также с авторитетными международными организациями. Диверсификационная стратегия национальной экономики государства и оснащение системы высокотехнологическими и цифровыми процессами даёт мощный импульс активному интегрированию в глобальное экономическое пространство и мирохозяйственные связи.
                            Туркменистан в условиях интенсивного развития национальной экономики придаёт большое значение сотрудничеству с государствами мира в области высоких технологий, внедрении современных передовых знаний и управленческих решений.
                            Проводится соответствующая работа по мерам реализации «Программы развития внешнеэкономической деятельности Туркменистана на 2020-2025 годы», «Стратегии внешней торговли Туркменистана на 2021-2030 годы», также другим документам, регулирующим торгово-экономическую и инвестиционную деятельность. В этом отношении, в качестве приоритетных выделяются задачи по созданию позитивных международных условий, способствующих устойчивому развитию национальной экономики и повышению благосостояния населения, активному участию в мирохозяйственных отношениях, дальнейшему развитию внешнеэкономических связей, привлечению в страну крупных инвестиций.
                            Президент Туркменистана Сердар Бердымухамедов, выступая 23 сентября 2022 года на Довлет Маслахаты, отметил, что в 2022-2028 годах средства Государственного бюджета будут направлены на обеспечение основных направлений социально-экономического роста и инновационного развития экономики. Значительная часть Госбюджета, как и прежде, будет использована для финансирования социальной сферы.
                            «В предстоящие семь лет мы существенно укрепим производственный потенциал страны, освоив инвестиции на сумму 278,9 миллиарда манатов. За этот период размеры заработной платы будут увеличены в 1,8 раза. Кроме этого, в отраслях экономики появится около 30 тысяч дополнительных рабочих мест. Общая площадь жилья на душу населения увеличится на 102,2 процента, будут построены 40 детских дошкольных учреждений, 54 средние школы, 4 заведения высшего профессионального образования, 10 современных больниц, 7 домов культуры, а также свыше 500 производственных и социальных объектов. В соответствии с нашим главным девизом «Родина является Родиной только с народом! Государство является государством только с народом!», являющимся продолжением принципа Героя-Аркадага «Государство для человека!», вся эта работа, в первую очередь, направлена на повышение благополучия родного народа и поступательное наращивание мощи Отчизны», - подчеркнул Президент Туркменистана.
                            Благодаря принятию средне- и долгосрочных государственных программ, в Туркменистане создана многоотраслевая экономика с развитой электроэнергетикой, нефтегазовой и нефтеперерабатывающей отраслями, химической и нефтехимической промышленностью, машиностроительной индустрией и металлоперерабатывающей отраслью, с объектами по производству строительных материалов, предприятиями лёгкой и пищевой промышленности.
                            В результате внедрения передовых научно-технических достижений, инкорпорированию лучшей мировой практики, достигнуты впечатляющие результаты в развитии агропромышленного комплекса и обеспечении продовольственного изобилия. В соответствии с Национальной сельской программой, в Туркменистане - родине «ак бугдая» - в 2022 году в закрома Отчизны сдано около 1 миллиона 500 тысяч тонн пшеницы. На более чем 60 текстильных предприятиях выпускаются различные виды хлопчатобумажной и комбинированной пряжи, ткани, готовая одежда, высококачественные ковры ручной работы, которые реализуются на мировом рынке. Сегодня Туркменистан также выпускает конкурентоспособную технику – смарт-телевизоры, ноутбуки, планшеты, моноблоки, компьютеры с сенсорными экранами.
                            По итогам шести месяцев 2022 года, макроэкономические показатели, по сравнению с аналогичными показателями шести месяцев предыдущего года, выросли по всем направлениям; за истёкший период были предприняты комплексные меры, направленные на обеспчение устойчивого развития всех отраслей экономики и регионов. ВВП увеличился на 6 процентов. Объём произведённой продукции, в сопоставлении с тем же периодом 2021 года, вырос на 11,5 процента. За шесть месяцев этого года показатель розничного товарооборота, в сравнении с аналогичным периодом прошлого года, больше на 10,4 процента, а внешнеторгового оборота на 40 процентов. Размеры заработной платы по крупным и средним предприятиям страныувеличились на 10,4 процента.
                            Одним из приоритетных направлений внешнеэкономической деятельности Туркменистана является активная и эффективная реализация Целей развития ООН. В стране ещё более расширяется международное сотрудничество в сфере энергетики и энергобезопасности, сфере устойчивого транспорта, экологии и охраны окружающей среды, в решении важных вопросов, касающихся водородной энергетики, продовольственной безопасности и другим направлениям.
                            Наша страна полностью удовлетворяет свои потребности в топливе и электроэнергии за счёт собственных ресурсов, значительную часть которых направляет на экспорт. Будучи приверженным весьма ответственному подходу к эффективной реализации колоссального энергетического потенциала в национальных интересах и во благо всего человечества, Туркменистан осуществляет в этом направлении конкретные шаги. Одним из ключевых векторов энергетической стратегии Туркменистана, занимающего четвёртое место в мире по запасам природного газа, является диверсификация его поставок на мировой рынок. Ярким свидетельством этого является принятие Генеральной Ассамблеей ООН Резолюций о надёжном и стабильном транзите энергоносителей.
                            Совместно с зарубежными партнёрами осваиваются месторождения на туркменском участке Каспия. Осуществляется строительство газопровода Туркменистан-Афганистан-Пакистан-Индия. Этот новый энергетический мост позволит долгосрочно поставлять туркменский природный газ в крупные страны Южной Азии и придаст мощный импульс социально-экономическому развитию, укреплению делового сотрудничества и мира во всём регионе.
                            Продолжается строительство станции по генерации солнечной и ветряной электроэнергии, внутреннего электрокольца и линии электропередачи по маршруту Туркменистан-Афганистан-Пакистан. Открытие в Ашхабаде Центра ремонта и сервисного обслуживания энергетического оборудования создаёт предпосылку для диверсификации сферы энергетики.
                            Реализуемая Туркменистаном транспортно-логистическая стратегия берёт свои истоки из древности – Великого Шёлкового пути. Сегодня Туркменистан осуществляет транспортно-транзитные коридоры по направлениям Север-Юг, Восток-Запад. Активно участвует в создании международных транспортных коридоров Туркменистан-Азербайджан-Грузия-Турция, Узбекистан-Туркменистан-Иран-Оман-Катар и ТРАСЕКА. Также реализованы проекты по строительству автомобильного и железнодоржного мостов через Амударью, международных аэровокзалов в городах Ашхабад, Туркменбаши, Туркменабат, Керки, Международного морского порта в Туркменбаши.
                            Туркменистан привлекательная страна с точки зрения привлечения инвестиций. Проделана огромная работа по активизации внутренней и внешней инвестиционной деятельности, укреплению экономического потенциала и обеспечению устойчивого социально-экономического развития регионов. Высоких оценок в международных рейтингах удостаиваются инициативы нашего государства, направленные на формирование благоприятного инвестиционного климата.
                            Туркменистан исходит из стратегических задач и программных документов по конкретным направлениям и остаётся приверженным всестороннему взаимовыгодному сотрудничеству с иностранными государствами, международными и региональными экономическими и финансовыми организациями и институтами; укрепляет позиции по реализации задач по данным векторам. Государство продолжает политику укрепления сотрудничества с Организацией экономического сотрудничества и развития, Международным валютным фондом, Группой Всемирного банка, Европейским банком реконструкции и развития, Азиатским банком развития, Исламским банком развития и другими финансово-экономическими структурами.
                            В последнее время весь мир видит индустриальный и интеллектуальный потенциал нашей страны посредством проведения торговых и финансовых форумов, ярмарок, симпозиумов, в том числе, виртуальных смотров. Достижения нашей страны удостоились высокой оценки на Всемирных выставках (ЭКСПО). С целью внедрения новых современных механизмов и моделей сотрудничества, реализуется ряд мер нацеленных на расширение партнёрства с Международным бюро выставок, а также активизация участиия в проводимых за рубежом выставках и ярмарках с национальной продукцией, услугами и промышленными образцами.
                            Туркменистан укрепляет широкое сотрудничество на глобальном и региональном уровнях и в энергетической сфере. В этом контексте, развивается взаимодействие с Международной Энергетической Хартией, Международным энергетическим агентством, Международным агентством по атомной энергии и Международным агентством по возобновляемым источникам энергии, а также с ведущими зарубежными компаниями, специализирующимися на производстве энергии.
                            Туркменистан проводит активную деятельность по интеграции в региональные и международные транспортные и информационно-коммуникационные системы, тем самым, развивая свои международные транспортно-транзитные возможности. В рамках действий по вступлению во Всемирную торговую организацию и в качестве государства, участвующего в международных договорах по свободной торговле, Туркменистан проводит эффективную торгово-экономическую стратегию. В качестве члена Комиссии ООН по праву международной торговли на период 2022-2028 годов, наша страна приступила к соответствующей работе в рамках данной структуры.
                            Активная деятельность в системе внешнеэкономического сотрудничества позволит укреплить позиции нашего государства в этом направлении, повысит его международный имидж как надёжного и ответственного партнёра, откроет новые возможности для освоения новых рынков и повышения притока иностранных инвестиций, а также расширит эффективное сотрудничество с мировыми финансовыми и торговыми структурами.
                            ',

            'content_en' => '«Berkarar döwletiň täze eýýamynyň Galkynyşy: Türkmenistany 2022-2052-nji ýyllarda durmuş-ykdysady taýdan ösdürmegiň Milli maksatnamasynyň» we «Türkmenistanyň Prezidentiniň ýurdumyzy 2022-2028-nji ýyllarda durmuş-ykdysady taýdan ösdürmek boýunça maksatnamasynyň» wezipelerine laýyklykda, Türkmenistanyň bitaraplyk syýasaty ählumumy strategik möhüm gural hökmünde dünýä we sebit döwletleri, şeýle hem abraýly halkara guramalary bilen hyzmatdaşlygy mundan beýläk-de ösdürmäge gönükdirilendir. Döwletiň milli ykdysadyýetiniň diwersifikasiýa ýoly bilen alnyp barylmagy we ulgamda ýokary tehnologiýalaryň we sanlylaşdyrma prosessleriniň ýaýbaňlandyrylmagy global ykdysady giňişligine we umumydünýä hojalyk gatnaşyklaryna işjeň goşuluşmagyna güýçli itergi berýär.
                            Türkmenistan milli ykdysadyýetiniň çalt depginler bilen ösýän şertlerinde dünýäniň dürli döwletleri bilen ýokary tehnologiýaly pudaklarda hyzmatdaşlyk etmäge, häzirki zamanyň öňdebaryjy bilimlerini we dolandyryş çözgütlerini ornaşdyrmaga uly ähmiýet berýär. «Türkmenistanyň 2020-2025-nji ýyllar üçin daşary ykdysady işiniň ösüşiniň maksatnamasyny», «Türkmenistanyň 2021-2030-njy ýyllar üçin daşary söwda strategiýasyny» we söwda, ykdysadyýet hem-de maýa goýumlar ulgamlaryna degişli resminamalardan gelip çykýan çäreleri hem-de taslamalary amala aşyrmak boýunça degişli işler alnyp barylýar. Bu babatda, milli ykdysadyýetiň durnukly ösüşine we ilatynyň durmuş derejesiniň ýokarlandyrylmagyna ýardam berýän oňyn halkara şertleri döretmek, dünýäniň hojalyk gatnaşyklaryna işjeň gatnaşmak, daşary ykdysady hyzmatdaşlygy has-da ösdürmek, iri maýa goýumlaryny ýurdumyza çekmek ýaly wajyp wezipeler ileri tutulýar.
                            Türkmenistanyň Prezidenti Serdar Berdimuhamedowyň 2022-nji ýylyň 23-nji sentýabrynda Döwlet maslahatynda eden çykyşynda belleýşi ýaly, 2022-2028-nji ýyllarda Döwlet býujetiniň serişdeleri durmuş-ykdysady ösüş strategiýany durmuşa geçirmegiň esasy ugurlaryna, ykdysadyýetiň innowasion ösüşini üpjün etmäge gönükdiriler. Býujetiň agramly böleginiň, ozalkylary ýaly, durmuş ulgamyny maliýeleşdirmek üçin sarp ediljekdigi nygtaldy.
                            «Geljek ýedi ýylda 278,9 milliard manatdan gowrak maýa goýumlaryny özleşdirip, ýurdumyzyň önümçilik kuwwatyny has-da pugtalandyrarys. Bu döwürde zähmet haklarynyň möçberlerini 1,8 esse artdyrarys. Ykdysadyýetimiziň ähli pudaklarynda 30 mü­ňe golaý goşmaça iş orunlaryny dörederis. Adam başyna düşýän ýaşaýyş jaýlarynyň umumy meýdanyny 102,2 göterim artdyrarys. Mekdebe çenli çagalar edaralarynyň 40-syny, orta mekdepleriň 54-sini, täze 4 sany ýokary hünär bilim edarasyny, 10 sany döwrebap hassahanany, 7 sany medeniýet öýüni, şol sanda 500-den gowrak täze önümçilik we durmuş maksatly binalardyr desgalary gurarys. Bu işleriň ählisi Gahryman Arkadagymyzyň «Döwlet adam üçindir!» diýen şygarynyň dowamy bolan «Watan di­ňe halky bilen Watandyr! Döwlet di­ňe halky bilen döwletdir!» diýen baş ýörelgämize laýyklykda, ilkinji nobatda, mähriban halkymyzyň abadançylygynyň ýokarlandyrylmagyna, ýurdumyzyň kuwwatynyň has-da artdyrylmagyna gönükdirilendir», - diýip, Türkmenistanyň Prezidenti belledi.
                            Orta we uzakmöhletleýin döwlet maksatnamalarynyň kabul edilmegi bilen, Türkmenistanda ösen elektroenergetika, nebit we gaz çykarýan, nebiti gaýtadan işleýän, himiýa we nebit-himiýa senagatlary, maşyn-gurluşyk we demiri gaýtadan işleýän, gurluşyk materiallaryny öndürýän desgalar, ýeňil we azyk senagatynyň kärhanalary bilen üpjün edilen köp pudakly dürli maksatly ykdysadyýet döredildi.
                            Ylmyň we tehnikanyň öň­debaryjy gazananlaryny, iň gowy dünýä tejribelerini ornaşdyrmak arkaly obasenagat toplumyny ösdürmekde we azyk bolçulygyny üpjün etmekde ýokary netijeler gazanylýar. Oba milli maksatnamasyna laýyklykda, ak bugdaýyň mekany bolan Türkmenistanda 2022-nji ýylda döwlet harmanyna 1 million 500 müň tonna golaý bugdaý tabşyryldy. Dokma kärhanalarynyň 60-dan gowragynda nah we garyşyk ýüplükleriň dürli görnüşleri, matalar, taýýar egin-eşikler, el halylary öndürilip, dünýä bazaryna ýokary hilli harytlar çykarylýar. Türkmenistan bu gün bäsdeşlige ukyply smart telewizorlary, noutbuklary, planşetleri, monobloklary, sensor ekranly kompýuterleri hem dünýä bazaryna ugradýar.
                            2022-nji ýylyň alty aýynyň makroykdysady görkezijileri boýunça Türkmenistanyň ykdysadyýetiniň geçen ýylyň alty aýynyň netijeleri bilen deňeşdirilende, ähli ugurlar boýunça ösüşe eýe bolandygyny, hemme pudaklaryň we sebitleriň durnukly ösüşini üpjün etmäge gönükdirilen toplumlaýyn çäreleriň amala aşyrylandygyny görkezýär. Jemi içerki önüm 6 göterim ýokarlandy. 2021-nji ýylyň degişli döwri bilen deňeşdirilende, jemi öndürilen önüm 11,5 göterim artdy. Şu ýylyň alty aýy boýunça bölek satuw haryt dolanyşygy 10,4 göterim, daşary söwda dolanyşygy bolsa, 40 göterim köpeldi. Ýurdumyzyň iri we orta kärhanalarynda ortaça aýlyk zähmet haky 10,4 göterim ýokarlandy.
                            Türkmenistanyň halkara ykdysady işiniň ileri tutulýan ugurlarynyň biri BMG-niň Ösüş maksatnamasyny durmuşa geçirmäge işjeň we netijeli gatnaşmaga gönükdirilendir. Ýurdumyzyň energetika we energiýa howpsuzlygy, durnukly ulag ulgamy, ekologiýa we daşky gurşawy goramak, hususan-da, wodorod energiýasy boýunça wajyp meseleleriň çözülmegi, azyk howpsuzlygy we beýleki ugurlar babatda halkara hyzmatdaşlyk has hem giňeldilýär.
                            Ýurdumyz dünýä döwletleriniň arasynda özüniň ýangyja we elektrik energiýasyna bolan isleglerini öz hususy baýlyklary bilen doly kanagatlandyrýar, şeýle hem onuň ep-esli bölegini daşary ýurtlara çykarýar. Türkmenistan milli we umumadamzat bähbitlerine özüniň ägirt uly energetika mümkinçiligini netijeli peýdalanmaga örän jogapkärli çemeleşmäge ygrarlylygyny bildirýär hem-de bu ugurda anyk wezipeleri ýerine ýetirýär. Tebigy gazyň gorlary boýunça dünýäde dördünji orny eýeleýän Türkmenistanyň energetika strategiýasynyň möhüm ugurlarynyň biri hem ony dünýä bazaryna ibermegi diwersifikasiýalaşdyrmakdan ybarat bolup durýar. BMG-niň Baş Assambleýasy tarapyndan energiýa serişdelerini ygtybarly we durnukly üstaşyr geçirmek baradaky Kararnamalarynyň kabul edilmegi hem muňa aýdyň subutnamadyr.
                            Daşary ýurtly hyzmatdaşlar bilen Hazaryň türkmen bölegindäki ýataklar özleşdirilýär. Türkmenistan-Owganystan-Pakistan-Hindistan gaz geçirijisiniň gurluşygy amala aşyrylýar. Bu täze energiýa köprüsi türkmen tebigy gazyny Günorta Aziýanyň iri ýurtlaryna uzak möhletleýin ugradylmagyny üpjün etmek bilen, tutuş sebitiň durmuş-ykdysady taýdan ösmegi, işewür hyzmatdaşlygyň, parahatçylygyň berkemegi üçin kuwwatly itergi bolup hyzmat eder.
                            Günden we ýelden elektrik energiýasyny öndürýän stansiýanyň, içerki energetika halkasynyň, Türkmenistan-Owganystan-Pakistan elektrik geçiriji ulgamynyň gurluşyklary dowam etdirilýär. Aşgabat şäherinde Energetika enjamlaryny abatlaýyş we hyzmat ediş merkeziniň açylmagy pudagy diwersifikasiýa ýoly bilen ösdürmek üçin şertleri döredýär.
                            Türkmenistanyň durmuşa geçirýän ulag-logistika strategiýasy öz gözbaşyny gadymyýetden - Beýik Ýüpek ýolundan alyp gaýdýar. Türkmenistan bu gün Demirgazyk-Günorta, Gündogar-Günbatar ugurlary boýunça üstaşyr ulag taslamalaryny amala aşyrýar. Türkmenistan-Azerbaýjan-Gruziýa-Türkiýe, Özbegistan-Türkmenistan-Eýran-Oman-Katar hem-de TRACEKA halkara ulag geçelgeleriniň döredilmegine işjeň gatnaşýar. Şeýle-de Amyderýanyň üstünden geçýän awtomobil we demir ýol köprülerini, Aşgabat, Türkmenbaşy, Türkmenabat, Kerki şäherlerinde Halkara howa menzillerini, Türkmenbaşy şäherinde Halkara de­ňiz portuny gurmak boýunça taslamalar amala aşyryldy.
                            Türkmenistan maýa goýumlar babatda hem özüne çekiji ýurtdur. Içerki we daşary ýurt maýa goýum işjeň­ligini artdyrmak, ýurduň sebitleriniň ykdysady kuwwatyny berkitmek hem-de durmuş-ykdysady taýdan durnukly ösüşini üpjün etmek babatda ägirt uly işler amala aşyrylýar. Döwletimiziň öňe sürýän amatly maýa goýum gurşawyny döretmek babatdaky başlangyçlaryna halkara reýtinglerde ýokary baha berilýär.
                            Türkmenistan anyk kesgitlenen ugurlar boýunça strategiki wezipelerden we maksatnamalaýyn resminamalardan ugur alýar we daşary ýurtlar, halkara we sebit ykdysady hem-de maliýe guramalary we institutlary bilen hemmetaraplaýyn özara bähbitli söwda-ykdysady gatnaşyklaryny dowam etmäge ygrarly we bu ugurda amala aşyrylmaly wezipeler boýunça tagallalary güýçlendirýär. Işjeň hyzmatdaşlygy alyp barmakda Ykdysady Hyzmatdaşlyk we Ösüş Guramasy, Halkara Pul Gaznasy, Bütindünýä Banky Topary, Ýewropanyň Täzeleniş we Ösüş Banky, Aziýa Ösüş Banky, Yslam Ösüş Banky we beýleki maliýe-ykdysady düzümler bilen gatnaşyklary pugtalandyrmak syýasatyny dowam edýär.
                            Soň­ky döwürde söwda we maliýe ugurlary boýunça forumlary, sergileri, ýarmarkalary, simpoziumlary, şol sanda, wirtual sergileri geçirmek bilen, ýurdumyzyň senagat we intellektual kuwwaty dünýä ýaýylýar. Dünýäniň iri ykdysady merkezlerinde geçirilen Bütindünýä «EKSPO» sergilerinde ýurdumyzyň ýeten derejesine ýokary baha berilýär. Halkara hyzmatdaşlygyň täze döwrebap gurallaryny we nusgalaryny ornaşdyrmak maksady bilen, Halkara sergiler býurosy bilen hyzmatdaşlygyň gerimini gi­ňeltmek boýunça çäreleri durmuşa geçirmek, daşary ýurtlarda guralýan sergilere we ýarmarkalara milli önümler, hyzmatlar, senagat nusgalar bilen gatnaşmagy işjeňleşdirmek ileri tutulýan wezipeleriň hatarynda durýar.
                            Türkmenistan energetika ulgamynda hem global we sebit derejelerinde giň hyzmatdaşlygyň pugtalandyrylmagy ugrunda Halkara Energetika Hartiýasy, Halkara Energetika agentligi, Atom energiýasy boýunca halkara agentligi, Energiýanyň gaýtadan dikeldilýän çeşmeleri boýunça halkara agentligi, şeýle hem energiýa serişdelerini öndüriji öňdebaryjy daşary ýurt kompaniýalary bilen hyzmatdaşlygy amala aşyrýar.
                            Türkmenistan sebit hem-de halkara ulag we maglumat-kommunikasiýa ulgamlaryna işjeň goşulmak ugrundaky işlerini dowam etmek bilen, özüniň halkara ulag-üstaşyr mümkinçiliklerini artdyrýar. Bütindünýä Söwda Guramasynyň agzalygyna girmek boýunça (häzirki wagtda «işjeň synçy» derejesinde) amala aşyrylýan hereketleriň çäklerinde hem-de erkin söwda boýunça halkara şertnamalara gatnaşýan ýurt hökmünde Türkmenistan söwda-ykdysady ugurly gyzyklanmalaryň ilerledilmegi babatynda işjeň syýasat alyp barýar. BMG-niň Halkara söwda hukugy boýunça komissiýasynyň 2022-2028-nji ýyllar döwri üçin agzasy hökmünde ýurdumyz onuň çäklerinde hem degişli işlere başlady.
                            Daşary ykdysady ulgamda alnyp barylýan tagallalar ýurdumyzyň dünýä hojalyk gatnaşyklaryndaky ornunyň pugtalandyrylmagyna, täze bazarlaryň özleşdirilmegine hem-de eksport mümkinçilikleriniň we daşary ýurt maýa goýumlarynyň artdyrylmagyna, türkmen harytlarynyň we hyzmatlarynyň dünýä bazaryna çykarylmagyna, halkara we sebit ykdysady hem-de maliýe guramalarynyň mümkinçilikleriniň doly göwrümde peýdalanylmagyna, şeýle-de dünýäniň ykdysady we maliýe bileleşikleriniň öňünde ýurdumyzyň oňyn abraýynyň kemala getirilmegine gönükdirilendir.
                            ',
        ]);
    }
}
