<?php

namespace Database\Seeders;

use App\Models\TkmForeignPolicy;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TkmForeignPolicySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        TkmForeignPolicy::create([
            'title_tm' => 'DAŞARY SYÝASAT',
            'title_ru' => 'ВНЕШНЯЯ ПОЛИТИКА',
            'title_en' => 'FOREIGN POLICY',
            
            'content_tm' => 'Garaşsyz, Hemişelik bitarap Türkmenistanyň daşary syýasaty Türkmenistanyň Konstitusiýasy, Türkmenistanyň konstitusion kanunlary, beýleki kadalaşdyryjy hukuk namalary, halkara hukugynyň umumy ykrar edilen ýörelgeleri we kadalary, şeýle hem Türkmenistanyň gatnaşýan halkara şertnamalary we konwensiýalary esasynda amala aşyrylýar.
                            Türkmenistan «Berkarar döwletiň täze eýýamynyň Galkynyşy: Türkmenistany 2022-2052-nji ýyllarda durmuş-ykdysady taýdan ösdürmegiň Milli maksatnamasynda» kesgitlenen, Türkmenistanyň Prezidentiniň derwaýys başlangyçlaryndan gelip çykýan, Türkmenistanyň Hökümeti tarapyndan daşary syýasatyň ösdürilmeginde ileri tutulýan uzakmöhletleýin we gysgamöhletleýin maksatlaryň hem-de wezipeleriň nazarda tutulmagynda hoşniýetli goňşuçylyga, deňhukuklylyk we birek-birege hormat goýmak, özara bähbitlilik ýörelgelerine esaslanýan halkara hyzmatdaşlygy dowam edýär.
                            Türkmenistan giň gerimli halkara hyzmatdaşlygyny durmuşa geçirmek we parahatsöýüjilik hem-de naýbaşy ynsanperwer gymmatlyklaryň ileri tutulmagy ýaly belent maksatlara eýermek bilen, parahatçylygy we howpsuzlygy üpjün etmek, ýurdumyzyň Hemişelik bitaraplyk hukuk ýagdaýyny halkara giňişliginde ýaýmak, daşary ykdysady gatnaşyklary okgunly giňeltmek we diwersifikasiýalaşdyrmak, durnukly ösüşe hem-de halkara gatnaşyklaryň has ynsanperwer bolmagyna ýardam bermek ýaly esasy wezipeleri ýerine ýetirimekden ugur alýar.
                            Türkmenistanyň daşary syýasy ugrunyň esasy maksatlary şulardan ybarat:
                            halkara parahatçylygy, howpsuzlygy hem-de durnukly ösüşi üpjün etmäge ýardam bermek;
                            dünýäniň syýasy giňişliginde Türkmenistanyň ornuny güýçlendirmek;
                            halkara gatnaşyklary ulgamynda döwletimiziň milli bähbitlerini yzygiderli goramak.
                            Şu belent maksatlardan ugur almak bilen, Türkmenistanyň daşary syýasatynyň öňünde howpsuzlygynyň toplumlaýyn we ygtybarly ulgamyny üpjün etmek, ýurduň garaşsyzlygyny we özygtyýarlylygyny berkitmek, şeýle-de Türkmenistanyň Hemişelik bitaraplyk hukuk derejesine gyşarnyksyz eýermek bilen, halkara parahatçylygyň, howpsuzlygyň we durnukly ösüşiň pugtalandyrylmagyna ýardam bermek ýaly wezipeler durýar.
                            Türkmenistan daşary ýurtlar bilen, şeýle hem halkara guramalaryň çäklerinde dostlukly, deňhukukly we özara bähbitli gatnaşyklary ösdürmäge we giňeltmäge, şeýle hem dünýäniň ykdysady we medeni-ynsanperwer giňişligine deňhukukly goşulmaga, bu gatnaşyklaryň mundan beýläk hem ösdürilmegine we diwersifikasiýalaşdyrylmagyna ýardam berjek zerur şertleri döretmäge ygrarlylygyny aýan edýär. Halkara meseleleri çözmegiň köpçülikleýin başlangyçlaryna, halkara hukugynyň hökmürowanlygyna, ilkinji nobatda, Birleşen Milletler Guramasynyň Tertipnamasynyň düzgünlerine, şeýle hem halkara gatnaşyklaryny kadalaşdyrýan esasy gurama hökmünde BMG-niň merkezi utgaşdyryjy ornunyň saklanylmagynda döwletleriň arasynda deňhukukly we özara bähbitli hyzmatdaşlyk gatnaşyklaryna esaslanýan adalatly we demokratik halkara ulgamyny kemala getirmek üçin halkara parahatçylygynyň, ählumumy howpsuzlygynyň we durnuklylygynyň hemmetaraplaýyn pugtalandyrylmagyna gönükdirilen ugry işjeň ýagdaýda ilerletmäge ýardam edýär.
                            Türkmenistan ikitaraplaýyn we köptaraplaýyn görnüşlerde dostlukly, açyk, köpugurly, milli bähbitleriň gapma-garşylyksyz ileri tutulmagyna hormat goýmak ýörelgelerine esaslanýan döwletara birleşikler we halkara düzümler hem-de forumlar bilen toplumlaýyn gatnaşyklary ösdürmekligi ileri tutýar.
                            Türkmen döwleti deňhukuklylyk, birek-birege hormat goýmak we özara bähbitli daşary syýasy strategiýasyny üstünlikli amala aşyrýar. Häzirki wagtda döwletimiz dünýäniň 151 ýurdy bilen diplomatik gatnaşyklaryny ýola goýdy.
                            Türkmenistan sebitiň ýurtlary bilen strategiki gatnaşyklaryny pugtalandyrmagy we ösdürmegi dowam edýär. Şol sanda, tebigy gazyň hem nebitiň eksportyny artdyrmak, sarp ediji we energiýa çeşmelerini üstaşyr geçirýän ýurtlar bilen deňhukukly dialogy dowam etmek, gaýtadan dikeldilýän energiýa çeşmeleri ulgamyndaky hyzmatdaşlygy amala aşyrmak arkaly energetika pudagynda ýola goýlan hyzmatdaşlygyň pugtalandyrylmagy boýunça hereketler işjeňleşdiriler.
                            Ýewropa bilen Aziýa-Ýuwaş ummany sebitleriniň arasynda söwda-ykdysady gatnaşyklaryň oňaýly ösdürilmegi maksady bilen, üstaşyr ýük akymlarynyň artdyrylmagy üçin özüniň geografiki taýdan amatly ýerleşişiniň ulanylmagy babatynda degişli çäreleri görer. Milli ykdysadyýetiň ösdürilmegi nukdaý nazaryndan, sebitiň ykdysady we maliýe guramalarynyň mümkinçiliklerinden işjeň hem netijeli peýdalanar.
                            Türkmenistan özüniň daşary syýasy strategiýasynda Ýakyn Gündogar sebitiniň ýurtlary bilen hyzmatdaşlygy mundan beýläk-de hemmetaraplaýyn pugtalandyrar, söwda-ykdysady, ynsanperwer gatnaşyklary ösdürmäge uly ähmiýet berer. Ýurdumyzyň daşary syýasatynyň esasy ugurlarynyň ýene-de biri – Afrika yklymynyň döwletleri bilen köptaraply, özara bähbitli dostlukly gatnaşyklary ösdürmek bolup durýar. Döwletimiziň Afrika ýurtlary bilen gatnaşyklarynda, ilki bilen, syýasy-diplomatik babatda örän gowy netijeler gazanylýar we bu ugurdaky wezipeleriň amala aşyrylmagy dowam etdiriler; ýanaşyk sebitleriň ýurtlarynyň üsti bilen söwda-ykdysady hyzmatdaşlyk mümkinçliklerini ýola goýmak möhüm meseleleriň hatarynda durýar.
                            Türkmenistan Demirgazyk Amerika sebitiniň ýurtlary bilen ikitaraplaýyn esasda we halkara derejesinde hyzmatdaşlygyny mundan beýläk-de giňeltmäge ygrarly. Syýasy dialogy ýokarlandyrmaga we özara bähbitli söwda we ykdysady hyzmatdaşlygy ösdürmäge ünsi çekip, Latyn Amerikasynyň ýurtlary we Karib deňzi ýurtlary bilen gatnaşyklary ikitaraplaýyn we köptaraplaýyn esasda ýola goýmak we berkitmek hem ileri tutulýan ugurlaryň biridir.
                            Türkmenistan sebitde, ilkinji nobatda, goňşy döwletler bilen özara gatnaşyklarynyň pugtalandyrylmagyna aýratyn üns berýär we dostluk, ynanyşmak, hoşniýetli goňşuçylyk we özara bähbitli hyzmatdaşlyk ýagdaýyny döretmäge tagalla edýär. Şunuň bilen baglylykda, ýurdumyz Merkezi Aziýa döwletleriniň gatnaşmagynda dürli görnüşdäki hyzmatdaşlyk formatlarynyň işiniň netijeliligini ýokarlandyrmaga işjeň goşant goşýar. Syýasy-diplomatik, ykdysady, söwda, ýangyç-energetika we ekologiýa, medeni-ynsanperwer ugurlarda halkara hyzmatdaşlygynyň häzirki zaman usullaryny işläp taýýarlamak boýunça halkara guramalar bilen bir hatarda «Merkezi Aziýa + 1» formatlaryň, şol sanda, «Merkezi Aziýa - Ýewropa Bileleşigi», «Merkezi Aziýa - Russiýa», «Merkezi Aziýa - ABŞ», «Merkezi Aziýa - Hytaý», «Merkezi Aziýa - Hindistan» «Merkezi Aziýa - Ýaponiýa», «Merkezi Aziýa - Koreýa Respublikasy» dialoglarynyň çäklerinde hem netijeli hyzmatdaşlyk dowam etdirilýär.
                            Türkmenistan 49 sany abraýly halkara we sebit guramalary bilen netijeli hem-de işjeň hyzmatdaşlygy alyp barmak bilen, parahatçylyk we ynanyşmak medeniýetiniň berkidilmegine, deňagramly hem-de birleşdiriji häsiýete eýe bolan global gün tertibiniň döredilmegine goşant goşýar. Birleşen Milletler Guramasynyň, Ýewropa Bileleşiginiň, Ýewropada Howpsuzlyk we Hyzmatdaşlyk Guramasynyň, Garaşsyz Döwletleriň Arkalaşygynyň, Yslam Hyzmatdaşlyk Guramasynyň, Goşulyşmazlyk Hereketiniň, Bütindünýä Saglygy Goraýyş Guramasynyň, Bütindünýä Syýahatçylyk Guramasynyň we beýleri halkara düzümleriň durmuşa geçirýän maksatnamalaryny, meýilnamalaryny we taslamalaryny maksatlaýyn ugurlara gönükdirip ulanmak işini giňden ýola goýmak bilen, hereket edýän halkara şertnamalar hem-de konwensiýalar boýunça öz halkara borçnamalaryny ýerine ýetirmäge wajyp wezipeler hökmünde garaýar.
                            Türkmenistan halkara bileleşiginiň jogapkär agzasy hökmünde hem-de öz bitaraplyk hukuk ýagdaýyna daýanmak bilen, halkara gatnaşyklarynda ynanyşmak dialogynyň filosofiýasyny ilerledýär hem-de «Dialog – parahatçylygyň kepili» atly ýörelgä pugta eýerýär. Şu nukdaý nazardan, ýurdumyz umumadamzat bähbitli halkara başlangyçlary durmuşa geçirmek boýunça işleriniň ählumumy ykrar edilmegi ugrundaky çäreleri işjeňleşdirmek, halkara gatnaşyklarynda «güýç ideologiýasynyň» ýaýradylmagyna we ykrar edilmegine syýasy-diplomatik taýdan yzygiderli garşy durmak, halkara gapma-garşylyklary çözmegiň ýeke-täk kabul ederlikli usuly hökmünde diplomatik gepleşikleri ykrar etmek ýaly garaýyşlardan ugur alýar.
                            Türkmenistan BMG-niň adamzat ýaşaýyş-durmuşynyň goragynyň üpjün edilmegini, adam hukuklarynyň, azatlyklarynyň kepillendirilmegini, syýasy-ykdysady çökgünligiň öňüniň alynmagyny, ýurtlaryň ösüş çygryndaky gazananlaryna hormat goýulmagyny gazanmak ugrundaky tagallalarynyň berkarar bolmagyna hem-de häzirki zaman wehimleriň we howplaryň öňüni almaga, olaryň täsirini peseltmäge gönükdürilen çäreleri amala aşyrmaga işjeň gatnaşýar.
                            ',

            'content_ru' => 'Внешняя политика Независимого, Постоянно нейтрального Туркменистана осуществляется на основе Конституции Туркменистана, конституционных законов Туркменистана, других регулирующих законодательных актов, общепринятых принципов и норм международного права, а также международных договоров и конвенций, в которых участвует Туркменистан.
                            Туркменистан продолжает международное сотрудничество на принципах добрососедства, равноправия, взаимоуважения и взаимовыгодного партнёрства, вытекающих из программы «Возрождение новой эпохи могущественного государства: Национальная программа социально-экономического развития Туркменистана в 2022-2052 годах» и важнейших инициатив Президента Туркменистана, а также с учётом приоритетных долгосрочных и краткосрочных целей и задач Правительства Туркменистана по развитию внешней политики.
                            Туркменистан, следуя высоким целям по претворению в жизнь широкомасштабного международного сотрудничества и, основываясь на приоритетности миролюбивых и высокогуманных ценностей, осуществляет курс на реализацию основных задач по обеспечению мира и безопасности, популяризацию правового статуса Постоянного нейтралитета страны на мировом пространстве, динамичное расширение и диверсификацию внешнеэкономических отношений, стабильное развитие и содействие гуманизации международных отношений.
                            Основными целями внешнеполитической стратегии Туркменистана являются:
                            содействие обеспечению международного мира, безопасности и устойчивого развития;
                            укрепление роли Туркменистана на мировом политическом пространстве;
                            последовательное отстаивание национальных интересов государства в системе международных отношений.
                            Следуя этим высоким целям, перед внешней политикой Туркменистана стоят задачи по обеспечению комплексной и надёжной системы безопасности Туркменистана, укреплению его независимости и суверенитета, а также неукоснительно следуя принципам правового статуса Постоянного нейтралитета Туркменистана, оказывать содействие укреплению международного мира, безопасности и устойчивого развития.
                            Туркменистан демонстрирует приверженность развитию и расширению дружественных, равноправных и взаимовыгодных отношений с зарубежными странами, а также в рамках международных организаций; равноправной интеграции в мировое экономическое и культурно-гуманитарное пространство, созданию необходимых условий по содействию дальнейшему развитию и диверсификации этих отношений. Активно содействует созданию справедливой и демократической международной системы, основанной на многоcторонних инициативах по решению глобальных вопросов, верховенстве международного права, прежде всего, принципов Устава Организации Объединённых Наций, а также сохранению центральной координирующей роли ООН в качестве основного регулирующего органа международных отношений в равноправном и взаимовыгодном сотрудничестве между государствами, направленном на активизацию вектора по всестороннему укреплению мира, всеобщей безопасности и стабильности.
                            Приоритетной задачей является развитие комплексных связей с межгосударственными объединениями, международными организациями и форумами, основанные на уважении принципов дружбы, открытости, многовекторности, с учётом приоритетности соблюдения национальных интересов при взаимодействии в двустороннем формате и в рамках международного сотрудничества.
                            Туркменистан успешно реализует равноправую, взаимоуважительную и основанную на обоюдных интересах внешнеполитическую стратегию. В настоящее время наше государство установило дипломатические связи со 151 страной мира.
                            Туркменистан продолжает укреплять и развивать стратегические отношения со странами региона. В том числе, активизируются действия по увеличению экспорта природного газа и нефти, продолжится равноправный диалог со странами-потребителями и странами-транзитёрами энергоносителей; путём реализации партнёрства в сфере возобновляемых источников энергии укрепится сотрудничество в энергетической отрасли. С целью оптимального развития торгово-экономических отношений между Европой и Азиатско-Тихоокеанским регионом, наше государство предпримет необходимые меры по эффективному использованию своего выгодного географического расположения для увеличения транзита грузовых потоков. С точки зрения развития национальной экономики, активно и плодотворно использует возможности региональных экономических и финансовых структур.
                            Туркменистан в своей внешнеполитической стратегии будет и в дальнейшем всесторонне укреплять сотрудничество со странами региона Ближнего Востока, будет придавать большое значение развитию торговых, экономических, гуманитарных отношений. Ещё одним из основных векторов внешней политики нашей страны – развитие многосторонних, взаимовыгодных и дружеских связей с государствами африканского континента. В отношениях нашего государства со странами Африки, прежде всего, достигнуты весьма хорошие результаты в политико-дипломатическом аспекте и будет продолжена реализация задач в данном контексте; в качестве основных вопросов выступит установление возможностей торгово-экономического сотрудничества через страны сопредельных регионов.
                            Туркменистан привержен дальнейшему расширению сотрудничества со странами Северной Америки как в двустороннем формате, так и на международном уровне. Уделяя внимание развитию политического диалога и взаимовыгодного торгового и экономического сотрудничества, одним из приоритетных направлений является установление и укрепление двусторонних и многосторонних связей со странами Латинской Америки и бассейна Карибского моря.
                            Туркменистан уделяет, прежде всего, особое внимание укреплению взаимоотношений с соседними по региону государствами и предпринимает усилия по созданию атмосферы дружбы, доверия, добрососедства и взаимовыгодного партнёрства. В этом контексте, Туркменистан вносит огромный вклад в повышение эффективности деятельности государств Центральной Азии в рамках различных форматов. В плане разработки современных методов международного сотрудничества в политико-дипломатическом, экономическом, торговом, топливно-энергетическом и экологическом, культурно-гуманитарном направлениях, наряду с международными организациями, продолжается эффективное и результативное взаимодействие в рамках диалога «Центральная Азия + 1», в т.ч., в форматах «Центральная Азия - Европейский Союз», «Центральная Азия - Россия», «Центральная Азия - США», «Центральная Азия - Китай», «Центральная Азия - Индия» «Центральная Азия - Япония», «Центральная Азия - Республика Корея».
                            Туркменистан реализует эффективное и активное сотрудничество с 49-ю международными и региональными организациями, тем самым, внося вклад в укрепление мира и культуры доверия, создание сбалансированной и объединяющей глобальной повестки дня. Проводя широкую деятельность по целенаправленному использованию программ, планов и проектов, реализуемых Организацией Объединённых Наций, Европейским Союзом, Организацией по Безопасности и Сотрудничеству в Европе, Содружеством Независимых Государств, Организацией Исламского Сотрудничества, Движением Неприсоединения, Всемирной Организацией Здравоохранения, Всемирной Туристической Организацией и другими международными структурами, рассматривает свои международные обязательства по действующим международным договорам и конвенциям в качестве важных задач.
                            Туркменистан как ответственный участник мирового сообщества и опираясь на свой правовой статус нейтрального государства, продвигает философию доверительного диалога в международных отношениях и твёрдо следует принципу «Диалог – гарантия мира». В этом контексте, наша страна руководствуется принципами по активизации мер, направленных на реализацию глобальных инициатив и использованию политико-дипломатического инструментария против распространения «силовой идеологии», демонстрирует приверженность дипломатическим переговорам как единственно принятому средству разрешения международных конфликтов и противоречий.
                            Туркменистан принимает активное участие в укреплении мер ООН, нацеленных на обеспечение социальной защищённости, гарантирование прав и свобод, предотвращение социально-экономического кризиса и противостояние современным вызовам и угрозам, а также уважительное отношение к достижениям государств в вопросах развития.
                            ',

            'content_en' => 'Garaşsyz, Hemişelik bitarap Türkmenistanyň daşary syýasaty Türkmenistanyň Konstitusiýasy, Türkmenistanyň konstitusion kanunlary, beýleki kadalaşdyryjy hukuk namalary, halkara hukugynyň umumy ykrar edilen ýörelgeleri we kadalary, şeýle hem Türkmenistanyň gatnaşýan halkara şertnamalary we konwensiýalary esasynda amala aşyrylýar.
                            Türkmenistan «Berkarar döwletiň täze eýýamynyň Galkynyşy: Türkmenistany 2022-2052-nji ýyllarda durmuş-ykdysady taýdan ösdürmegiň Milli maksatnamasynda» kesgitlenen, Türkmenistanyň Prezidentiniň derwaýys başlangyçlaryndan gelip çykýan, Türkmenistanyň Hökümeti tarapyndan daşary syýasatyň ösdürilmeginde ileri tutulýan uzakmöhletleýin we gysgamöhletleýin maksatlaryň hem-de wezipeleriň nazarda tutulmagynda hoşniýetli goňşuçylyga, deňhukuklylyk we birek-birege hormat goýmak, özara bähbitlilik ýörelgelerine esaslanýan halkara hyzmatdaşlygy dowam edýär.
                            Türkmenistan giň gerimli halkara hyzmatdaşlygyny durmuşa geçirmek we parahatsöýüjilik hem-de naýbaşy ynsanperwer gymmatlyklaryň ileri tutulmagy ýaly belent maksatlara eýermek bilen, parahatçylygy we howpsuzlygy üpjün etmek, ýurdumyzyň Hemişelik bitaraplyk hukuk ýagdaýyny halkara giňişliginde ýaýmak, daşary ykdysady gatnaşyklary okgunly giňeltmek we diwersifikasiýalaşdyrmak, durnukly ösüşe hem-de halkara gatnaşyklaryň has ynsanperwer bolmagyna ýardam bermek ýaly esasy wezipeleri ýerine ýetirimekden ugur alýar.
                            Türkmenistanyň daşary syýasy ugrunyň esasy maksatlary şulardan ybarat:
                            halkara parahatçylygy, howpsuzlygy hem-de durnukly ösüşi üpjün etmäge ýardam bermek;
                            dünýäniň syýasy giňişliginde Türkmenistanyň ornuny güýçlendirmek;
                            halkara gatnaşyklary ulgamynda döwletimiziň milli bähbitlerini yzygiderli goramak.
                            Şu belent maksatlardan ugur almak bilen, Türkmenistanyň daşary syýasatynyň öňünde howpsuzlygynyň toplumlaýyn we ygtybarly ulgamyny üpjün etmek, ýurduň garaşsyzlygyny we özygtyýarlylygyny berkitmek, şeýle-de Türkmenistanyň Hemişelik bitaraplyk hukuk derejesine gyşarnyksyz eýermek bilen, halkara parahatçylygyň, howpsuzlygyň we durnukly ösüşiň pugtalandyrylmagyna ýardam bermek ýaly wezipeler durýar.
                            Türkmenistan daşary ýurtlar bilen, şeýle hem halkara guramalaryň çäklerinde dostlukly, deňhukukly we özara bähbitli gatnaşyklary ösdürmäge we giňeltmäge, şeýle hem dünýäniň ykdysady we medeni-ynsanperwer giňişligine deňhukukly goşulmaga, bu gatnaşyklaryň mundan beýläk hem ösdürilmegine we diwersifikasiýalaşdyrylmagyna ýardam berjek zerur şertleri döretmäge ygrarlylygyny aýan edýär. Halkara meseleleri çözmegiň köpçülikleýin başlangyçlaryna, halkara hukugynyň hökmürowanlygyna, ilkinji nobatda, Birleşen Milletler Guramasynyň Tertipnamasynyň düzgünlerine, şeýle hem halkara gatnaşyklaryny kadalaşdyrýan esasy gurama hökmünde BMG-niň merkezi utgaşdyryjy ornunyň saklanylmagynda döwletleriň arasynda deňhukukly we özara bähbitli hyzmatdaşlyk gatnaşyklaryna esaslanýan adalatly we demokratik halkara ulgamyny kemala getirmek üçin halkara parahatçylygynyň, ählumumy howpsuzlygynyň we durnuklylygynyň hemmetaraplaýyn pugtalandyrylmagyna gönükdirilen ugry işjeň ýagdaýda ilerletmäge ýardam edýär.
                            Türkmenistan ikitaraplaýyn we köptaraplaýyn görnüşlerde dostlukly, açyk, köpugurly, milli bähbitleriň gapma-garşylyksyz ileri tutulmagyna hormat goýmak ýörelgelerine esaslanýan döwletara birleşikler we halkara düzümler hem-de forumlar bilen toplumlaýyn gatnaşyklary ösdürmekligi ileri tutýar.
                            Türkmen döwleti deňhukuklylyk, birek-birege hormat goýmak we özara bähbitli daşary syýasy strategiýasyny üstünlikli amala aşyrýar. Häzirki wagtda döwletimiz dünýäniň 151 ýurdy bilen diplomatik gatnaşyklaryny ýola goýdy.
                            Türkmenistan sebitiň ýurtlary bilen strategiki gatnaşyklaryny pugtalandyrmagy we ösdürmegi dowam edýär. Şol sanda, tebigy gazyň hem nebitiň eksportyny artdyrmak, sarp ediji we energiýa çeşmelerini üstaşyr geçirýän ýurtlar bilen deňhukukly dialogy dowam etmek, gaýtadan dikeldilýän energiýa çeşmeleri ulgamyndaky hyzmatdaşlygy amala aşyrmak arkaly energetika pudagynda ýola goýlan hyzmatdaşlygyň pugtalandyrylmagy boýunça hereketler işjeňleşdiriler.
                            Ýewropa bilen Aziýa-Ýuwaş ummany sebitleriniň arasynda söwda-ykdysady gatnaşyklaryň oňaýly ösdürilmegi maksady bilen, üstaşyr ýük akymlarynyň artdyrylmagy üçin özüniň geografiki taýdan amatly ýerleşişiniň ulanylmagy babatynda degişli çäreleri görer. Milli ykdysadyýetiň ösdürilmegi nukdaý nazaryndan, sebitiň ykdysady we maliýe guramalarynyň mümkinçiliklerinden işjeň hem netijeli peýdalanar.
                            Türkmenistan özüniň daşary syýasy strategiýasynda Ýakyn Gündogar sebitiniň ýurtlary bilen hyzmatdaşlygy mundan beýläk-de hemmetaraplaýyn pugtalandyrar, söwda-ykdysady, ynsanperwer gatnaşyklary ösdürmäge uly ähmiýet berer. Ýurdumyzyň daşary syýasatynyň esasy ugurlarynyň ýene-de biri – Afrika yklymynyň döwletleri bilen köptaraply, özara bähbitli dostlukly gatnaşyklary ösdürmek bolup durýar. Döwletimiziň Afrika ýurtlary bilen gatnaşyklarynda, ilki bilen, syýasy-diplomatik babatda örän gowy netijeler gazanylýar we bu ugurdaky wezipeleriň amala aşyrylmagy dowam etdiriler; ýanaşyk sebitleriň ýurtlarynyň üsti bilen söwda-ykdysady hyzmatdaşlyk mümkinçliklerini ýola goýmak möhüm meseleleriň hatarynda durýar.
                            Türkmenistan Demirgazyk Amerika sebitiniň ýurtlary bilen ikitaraplaýyn esasda we halkara derejesinde hyzmatdaşlygyny mundan beýläk-de giňeltmäge ygrarly. Syýasy dialogy ýokarlandyrmaga we özara bähbitli söwda we ykdysady hyzmatdaşlygy ösdürmäge ünsi çekip, Latyn Amerikasynyň ýurtlary we Karib deňzi ýurtlary bilen gatnaşyklary ikitaraplaýyn we köptaraplaýyn esasda ýola goýmak we berkitmek hem ileri tutulýan ugurlaryň biridir.
                            Türkmenistan sebitde, ilkinji nobatda, goňşy döwletler bilen özara gatnaşyklarynyň pugtalandyrylmagyna aýratyn üns berýär we dostluk, ynanyşmak, hoşniýetli goňşuçylyk we özara bähbitli hyzmatdaşlyk ýagdaýyny döretmäge tagalla edýär. Şunuň bilen baglylykda, ýurdumyz Merkezi Aziýa döwletleriniň gatnaşmagynda dürli görnüşdäki hyzmatdaşlyk formatlarynyň işiniň netijeliligini ýokarlandyrmaga işjeň goşant goşýar. Syýasy-diplomatik, ykdysady, söwda, ýangyç-energetika we ekologiýa, medeni-ynsanperwer ugurlarda halkara hyzmatdaşlygynyň häzirki zaman usullaryny işläp taýýarlamak boýunça halkara guramalar bilen bir hatarda «Merkezi Aziýa + 1» formatlaryň, şol sanda, «Merkezi Aziýa - Ýewropa Bileleşigi», «Merkezi Aziýa - Russiýa», «Merkezi Aziýa - ABŞ», «Merkezi Aziýa - Hytaý», «Merkezi Aziýa - Hindistan» «Merkezi Aziýa - Ýaponiýa», «Merkezi Aziýa - Koreýa Respublikasy» dialoglarynyň çäklerinde hem netijeli hyzmatdaşlyk dowam etdirilýär.
                            Türkmenistan 49 sany abraýly halkara we sebit guramalary bilen netijeli hem-de işjeň hyzmatdaşlygy alyp barmak bilen, parahatçylyk we ynanyşmak medeniýetiniň berkidilmegine, deňagramly hem-de birleşdiriji häsiýete eýe bolan global gün tertibiniň döredilmegine goşant goşýar. Birleşen Milletler Guramasynyň, Ýewropa Bileleşiginiň, Ýewropada Howpsuzlyk we Hyzmatdaşlyk Guramasynyň, Garaşsyz Döwletleriň Arkalaşygynyň, Yslam Hyzmatdaşlyk Guramasynyň, Goşulyşmazlyk Hereketiniň, Bütindünýä Saglygy Goraýyş Guramasynyň, Bütindünýä Syýahatçylyk Guramasynyň we beýleri halkara düzümleriň durmuşa geçirýän maksatnamalaryny, meýilnamalaryny we taslamalaryny maksatlaýyn ugurlara gönükdirip ulanmak işini giňden ýola goýmak bilen, hereket edýän halkara şertnamalar hem-de konwensiýalar boýunça öz halkara borçnamalaryny ýerine ýetirmäge wajyp wezipeler hökmünde garaýar.
                            Türkmenistan halkara bileleşiginiň jogapkär agzasy hökmünde hem-de öz bitaraplyk hukuk ýagdaýyna daýanmak bilen, halkara gatnaşyklarynda ynanyşmak dialogynyň filosofiýasyny ilerledýär hem-de «Dialog – parahatçylygyň kepili» atly ýörelgä pugta eýerýär. Şu nukdaý nazardan, ýurdumyz umumadamzat bähbitli halkara başlangyçlary durmuşa geçirmek boýunça işleriniň ählumumy ykrar edilmegi ugrundaky çäreleri işjeňleşdirmek, halkara gatnaşyklarynda «güýç ideologiýasynyň» ýaýradylmagyna we ykrar edilmegine syýasy-diplomatik taýdan yzygiderli garşy durmak, halkara gapma-garşylyklary çözmegiň ýeke-täk kabul ederlikli usuly hökmünde diplomatik gepleşikleri ykrar etmek ýaly garaýyşlardan ugur alýar.
                            Türkmenistan BMG-niň adamzat ýaşaýyş-durmuşynyň goragynyň üpjün edilmegini, adam hukuklarynyň, azatlyklarynyň kepillendirilmegini, syýasy-ykdysady çökgünligiň öňüniň alynmagyny, ýurtlaryň ösüş çygryndaky gazananlaryna hormat goýulmagyny gazanmak ugrundaky tagallalarynyň berkarar bolmagyna hem-de häzirki zaman wehimleriň we howplaryň öňüni almaga, olaryň täsirini peseltmäge gönükdürilen çäreleri amala aşyrmaga işjeň gatnaşýar.
                            ',
        ]);
    }
}
