<?php

namespace Database\Seeders;

use App\Models\TkmSport;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TkmSportSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        TkmSport::create([
            'title_tm' => 'TÜRKMENISTANYŇ HALKARA SPORT HYZMATDAŞLYGY',
            'title_ru' => 'СПОРТ И МЕЖДУНАРОДНОЕ СПОРТИВНОЕ СОТРУДНИЧЕСТВО ТУРКМЕНИСТАНА',
            'title_en' => 'SPORT AND INTERNATIONAL SPORT COOPERATION OF TURKMENISTAN',
            
            'content_tm' => 'Bedenterbiýe we sport jemgyýetiň sagdynlygyny üpjün edýän gymmatlykdyr.
                            Türkmenistanda bu ulgamy ösdürmek döwlet syýasatynyň ileri tutulýan ugurlarynyň biri bolup durýar. Öňde goýlan wezipeleri amala aşyrmak maksady bilen, ýurtda bu ugurdaky hereketleriň täze usullary kemala getirilýär, ussat türgenleri taýýarlamak ugrunda toplumlaýyn özgertmeler amala aşyrylýar, Olimpiýa hereketiniň ösdürilmegine uly goşant goşulýar. Ýurdumyzda bedenterbiýäniň we sportuň kämilleşmegi, adamyň kuwwatynyň maddy we ruhy taýdan sazlaşykly utgaşmagy netijesinde sagdyn durmuş ýörelgelerine eýe bolmagy, şeýle-de sport boýunça halkara hyzmatdaşlygyň has-da giňelmegi döwlet syýasatynyň ileri tutulýan ugurlarynyň biri boldy.
                            Ýurduň ähli welaýatlarynda köpugurly stadionlar, bedenterbiýe we sagaldyş toplumlary, aýlawlar, sport mekdepleri we beýleki desgalar bina edildi we ulanmaga berildi. Türgenlerdir hünärmenleri, tälimçileri taýýarlamagyň täze usullary we sport oýunlaryny geçirmegiň tejribesi kämilleşdirildi. Türkmen sport ussatlary daşary ýurtlarda geçirilýän ýaryşlara işjeň gatnaşýarlar.
                            Türkmenistanda sportuň gyşky görnüşleri bilen meşgullanmaga hem giň mümkinçilikler döredilen. Aşgabatda Sportuň gyşky görnüşleri boýunça sport toplumy, Golf sport toplumy, dünýä ölçeglerine laýyk gelýän Türkmen döwlet bedenterbiýe we sport instituty, «Awaza» milli syýahatçylyk zolagynda uly göwrümli buz meýdançalaryndan ybarat bolan köpugurly sport toplumy guruldy. Ýurdumyzda hokkeý boýunça milli çempionat oýunlary geçirilýär, şeýle hem sportuň figuralaýyn buzda typmak we şort-trek ýaly görnüşleri ösdürilýär. Ýurdumyzda şaýbaly hokkeý boýunça hem çempionatlar geçirilýär. Türkmenistanyň hokkeý boýunça ýygyndy topary halkara derejesine çykdy.
                            Sport ulgamynda amala aşyrylýan özgertmeler sport ussatlygyň ýokary derejelere çykmagyna hem ýardam edýär. Bedenterbiýäniň we sportuň ösüşi «Bedenterbiýe we sport hakynda», «Professional sport hakynda», «Atçylyk we atçylyk sport ýaryşlary hakynda», «Ýaşlar barada döwlet syýasaty hakynda», «Meýletinçilik hakynda», şeýle-de «Sportda dopinge garşy göreş hakynda» Türkmenistanyň Kanunlarynda berkidilen.
                            Bu ugurda halkara hyzmatdaşlygyny has-da berkitmek, şeýle hem bütindünýä olimpiýa hereketine goşulyşmak üçin Türkmenistan BMG-niň Bilim, ylym we medeniýet boýunça ýöriteleşdirilen edarasynyň sportda doping serişdelerini ulanmaklyga garşy göreşi boýunça Halkara Konwensiýasyny tassyklady, Olimpiýa nyşanlaryny gorap saklamak baradaky Naýrobi ylalaşygyna goşuldy. Ýurtda Milli antidoping agentligi döredildi.
                            Türkmenistan halkara sport hyzmatdaşlygy düşünjesine ýokary ynsanperwer manyny berýär we ony gönüden-göni BMG-niň 2030-njy ýyla çenli Durnukly Ösüş Maksatlarynyň kabul edilmegi bilen baglanyşdyrýar. 2017-nji ýylyň 15-nji sentýabrynda BMG-niň Adam hukuklary boýunça geňeşiniň 36-njy mejlisinde Türkmenistanyň başlangyjy bilen, «Bosgunlaryň olimpik ýygyndysynyň parahatçylygy we adam hukuklaryny berkitmek boýunça gymmatly goşandyny höweslendirmek boýunça» atly ýüzlenme kabul edildi. Biziň ýurdumyzyň başlangyjy esasynda, BMG-niň Baş Assambleýasy 3-nji iýuny Bütindünýä welosiped güni hökmünde yglan etdi.
                            Türkmenistanda sportda netijeli halkara hyzmatdaşlygy alyp barmagyň düýp esaslary goýuldy. Şu babatda, 60-dan gowrak döwlet bilen ikitaraplaýyn esasda sport ulgamyndaky hyzmatdaşlyk hereketleri düzgünleşdirilýär. Bulardan başga-da, sport boýunça hyzmatdaşlyk meselesi döwlet baştutanlarynyň saparlarynyň dowamynda kabul edilýän jarnamalarda we beýannamalarda, şeýle hem ykdysady hyzmatdaşlygy ösdürmek boýunça hökümetara bilelikdäki toparlaryň jemleýji resminamalarynda öz mynasyp ornuny tapýar.
                            Halkara sport hyzmatdaşlygy ulgamynda hem-de sport diplomatiýasyny ösdürmek boýunça esasy möhüm ugurlaryň biri hem dünýäde türkmen milli göreşini yzygider ýaýratmak bolup durýar. 2015-nji ýyldan başlap Aşgabatda Bütindünýä göreş federasiýasynyň ştab-kwartirasy öz işine başlady. Sportuň bu görnüşi boýunça milli federasiýalar 20-den gowrak döwletde hereket edýär. 2017-nji ýylda Ýewropa, Afrika we Günorta Amerikanyň yklym federasiýalary döredildi we türkmen milli göreşi boýunça Ýewropanyň we Afrikanyň çempionatlary geçirildi. Türkmen milli göreşini dünýä ýaýratmak ugrundaky işler häzirki wagtda hem dowam etdirilýär.
                            Türkmenistan halkara sport hyzmatdaşlygynyň merkezleriniň biri hökmünde ykrar edildi. Bu işjeň hyzmatdaşlygyň çäklerinde Halkara Olimpiýa Komiteti, BMG-niň Ösüşiň we parahatçylygyň hatyrasyna sport boýunça halkara býurosy, ÝUNESKO-nyň Bedenterbiýe we sport boýunça hökümetara komiteti, Aziýanyň Olimpiýa Geňeşi bilen parahatçylygyň we ynsanperwerligiň pugtalandyrylmagyny şertlendirýän gatnaşyklaryň gerimi giňeýär.
                            2017-nji ýylyň 17-27-nji sentýabrynda Aşgabatda «Sagdynlyk. Ruhubelentlik. Dostluk» şygary astynda Ýapyk binalarda we söweş sungaty boýunça V Aziýa oýunlary geçirildi. «Aşgabat-2017-niň» ýaryşlaryna 45 sany Aziýa döwletlerinden hem-de Okeaniýanyň 19 döwletinden (dünýä döwletleriniň üçden bir bölegine barabar) türgenler gatnaşdy. Bu ýaryşlara bosgunlaryň sport topary hem şeýle derejedäki bäsleşige ilkinji gezek gatnaşdy.
                            Bäsleşikler Aşgabatda Oýunlar üçin ýörite gurlan, Merkezi Aziýa sebitinde deňi-taýy bolmadyk Olimpiýa şäherçesinde geçirildi. Şäherçede 40-dan gowrak dürli desgalar gurlyp, olaryň ikisi Ginnesiň Bütindünýä rekordlar kitabyna girizildi - Olimpiýa stadionynyň ýokarsynda ýerleşdirilen atyň dünýäde iň uly çeper-monumental şekili we dünýäde üsti ýapyk iň uly sportuň suw görnüşleriniň toplumydyr.
                            Geçirilen halkara derejesindäki iri ýaryşlaryň arasynda «Amul-Hazar-2018» awtorallisi, Agyr atletika boýunça 2018-nji ýylyň dünýä çempionaty, Beýik ýüpek ýolunuň ugry boýunça ylgaw ýaryşlary hem-de köpçülikleýin welosipedli ýörişler, Hazarýaka döwletleriň mekdep medeni-sport festiwaly we ş.m. bar. 2009-njy ýylda «Ýüpek ýoly» ralli ýaryşy geçirildi, onuň ýoly Türkmenistanyň, Gazagystanyň we Russiýanyň çäklerinden geçdi. 2014-nji ýylda «Awaza» milli syýahatçylyk zolagynda windsýorfing boýunça dünýä kubogy ugrundaky ýaryşyň tapgyrynyň geçirilmegi bilen, ýurdumyz ilkinji gezek ýelkenli sport boýunça halkara ýaryşlaryň senenamasyna girdi.
                            Ýaponiýada 2021-nji ýylda geçirilen XXXII tomusky Olimpiýa oýunlarynda Türkmenistanyň milli ýygyndy toparynyň türgenleriniň mynasyp wekilçilik etmekleri, ýurduň sport taryhynda ilkinji Olimpiýa medalynyň gazanylmagy döwletimizde sporty ösdürmäge uly üns berilýändigine şaýatlyk edýär. Türkmen döwlet bedenterbiýe we sport institutynda, Aşgabatdaky Olimpiýa şäherçesinde döredilen şertlerden hem-de innowasion mümkinçiliklerden ugur alyp, 2024-nji ýylda Parižde geçiriljek XXXIII tomusky Olimpiýa we XVII tomusky Paralimpiýa oýunlaryna, beýleki halkara ýaryşlara Türkmenistanyň milli ýygyndy toparlary taýynlyk görýärler.
                            Türkmenistan sebit we dünýäde rejesindäki iri sport ýaryşlary guramak hem-de geçirmek üçin uly tejribä hem mümkinçilige eýedir. Halkara ýaryşlara işjeň gatnaşýan türkmen türgenleriniň gazanýan üstünlikleri we ýeňişleri bu ulgamda durmuşa geçirilýän strategiýanyň netijeliliginiň aýdyň subutnamasydyr. Bularyň ählisi Türkmenistanyň dünýä derejesinde sport döwleti hökmünde abraýynyň has-da ýokarlanmagyna ýardam edýär.
                            ',

            'content_ru' => 'Физическая культура и спорт являются главной ценностью, обеспечивающей общественное здоровье и благополучие. В этом контексте, в Туркменистане осуществляются комплексные преобразования, призванные способствовать активизации физкультурно-оздоровительного движения и подготовке высококлассных спортсменов, вносится большой вклад в дело популяризации принципов международного олимпийского движения. Совершествование сферы физической культуры и спорта, развитие принципов здорового образа жизни, также последовательное расширение международного спортивного сотрудничества являются одними из приоритетных задач государственной политики Туркменистана.
                            Во всех велаятах страны построены многофункциональные стадионы, физкультурно-оздоровительные комплексы, ипподромы, спортивные школы и другие сооружения. Совершествовалась методика подготовки спортсменов и специалистов, практика проведения спортивных соревнований. Туркменские спортсмены стали активно участвовать в зарубежных турнирах.
                            В Туркменистане созданы широкие возможности и для занятий зимними видами спорта. В Ашхабаде построен Спортивный комплекс зимних видов спорта, Спортивный комплекс по гольфу, соответствующий мировым стандартам Туркменский государственный институт физической культуры и спорта, в Национальной туристической зоне «Аваза» - многофункциональный спортивный комплекс с ледовой ареной профессиональных размеров. В стране проводятся национальные чемпионаты по хоккею, а также фигурному катанию и шорт-треку. Также проводятся турниры по хоккею с шайбой. За последние годы сборная Туркменистана по хоккею вышла международный уровень.
                            За годы преобразований существенно выросло качество спортивного мастерства. Развитие физкультуры и спорта подкреплены Законами Туркменистана «О физической культуре и спорте», «О профессиональном спорте», «О коневодстве и конноспортивных соревнованиях», «О государственной молодёжной политике», «О волонтёрстве», «О борьбе с допингом в спорте».
                            С целью укрепления международного сотрудничества в этом направлении, а также включения во всемирное олимпийское движение, Туркменистан ратифицировал Международную конвенцию ЮНЕСКО по борьбе с допингом в спорте, присоединился к Найробскому договору об охране олимпийских символов и создал Национальное антидопинговое агентство.
                            В понятие международного спортивного сотрудничества Туркменистан вкладывает высокий гуманистический смысл и напрямую связывает его с принятыми в ООН Целями устойчивого развития до 2030 года. 15 сентября 2017 гоадпо инициативе Туркменистана на 36-й сессии Совета ООН по правам человека была принята Декларация «О поощрении ценного вклада Олимпийских команд беженцев в укрепление мира и прав человека». По инициативе нашей страны Генеральная Ассамблея ООН провозгласила 3 июня как Всемирный день велосипеда.
                            В Туркменистане заложены прочные основы международного спортивного сотрудничества. В этом отношении, на двусторнней правовой основе регулируется сотрудничество в области спорта более чем с 60-ю государствами мира. Кроме того, вопросы спортивного сотрудничества находят достойное место в принимаемых по итогам визитов но высшем уровне деклараций и заявлений глав государств, а также в итоговых документах межправительственных комиссий по развитию двустороннего сотрудничества с зарубежными странами.
                            Одним из важнейших направлений в области международного спортивного сотрудничества и развития спортивной дипломатии стала последовательная деятельность по популяризации национальной борьбы гореш в мире. Начиная с 2015 года, действует Всемирная федерация борьбы гореш со штаб-квартирой в Ашхабаде, а национальные федерации по этому виду спорта созданы более чем в 20-ти странах. В 2017 году созданы также Европейская, Африканская и Южно-американская континентальные федерации и проведены чемпионаты Европы и Африки по туркменской национальной борьбе гореш. Работа по дальнейшему продвижению туркменской национальной борьбы гореш в мире продолжается.
                            Туркменистан признан в качестве одного из центров международного спортивного сотрудничества. В рамках этого расширяется взаимодействие с Международным Олимпийским комитетом, Бюро ООН по спорту на благо развития и мира, Межправительственным комитетом ЮНЕСКО по физической культуре и спорту, Олимпийским советом Азии. Наша страна регулярно выступает с конкретными предложениями, направленными на развитие взаимополезного сотрудничества в данном направлении и поддержку олимпийского движения как важного фактора упрочения всеобщего мира, дружбы и добрососедства.
                            17-27 сентября 2017 года в Ашхабаде под лозунгом «Здоровье. Воодушевление. Дружба» состоялись V Азиатские игры в закрытых помещениях и по боевым искусствам. В Играх «Ашхабад-2017» приняли участие спортсмены из 45 стран Азии и из 19-ти стран Океании (почти одна треть государств мира). Впервые на соревнованиях такого уровня приняла участие спортивная команда беженцев. Соревнования проходили в специально построенном к Играм в Ашхабаде уникальном, не имеющем аналогов в Центральноазиатском регионе Олимпийском городке, в котором было сооружено около 40 различных объектов. Два из них включены в Книгу рекордов Гиннеса – самое большое в мире художественно-монументальное изображение коня, возвышающееся над трибуной Олимпийского стадиона и комплекс водных видов спорта с самым большим в мире крытым плавательным бассейном.
                            В Туркменистане прошли такие крупные международные соревнования как авторалли «Амуль-Хазар-2018», Чемпионат мира по тяжёло й атлетике в 2018 году, легкоатлетический кросс и массовый веломарафон по маршруту Великого шёлкового пути, Школьный культурно-спортивный фестиваль Прикаспийских государств и др.
                            В 2009 году состоялось ралли «Шёлковый путь», пролегавшее через территории Туркменистана, Казахстана и России. В 2014 году в Национальной туристической зоне «Аваза» прошёл этап соревнований за мировой кубок по виндсёрфингу, таким образом, наша страна впервые вошла в летопись международных состязаний по парусным видам спорта.
                            Достойное участие представительной спортивной команды из Туркменистана на XXXII летних Олимпийских играх в Японии в 2021 году и завоевание первой в истории туркменского спорта олимпийской медали стало знаменательным событием, свидетельствующим о большом внимании со стороны государства развитию спорта. Исходя из созданных условий и инновационных возможностей в Туркменском государственном институте физической культуры и спорта, а также в Олимпийском городке в Ашхабаде, на научной основе разработана программа подготовки сборных команд Туркменистана к XXXIII летним Олимпийским играм и XVII летним Паралимпийским играм, которые пройдут в 2024 году в Париже, а также к другим международным спортивным соревнованиям.
                            Туркменистан имеет большой опыт и возможности для организации и проведения крупных спортивных мероприятий регионального и международного уровня. Успехи и победы туркменских спортсменов на международных соревнованиях являются ярким свидетельством эффективности проводимой в этом направлении стратегии государства. Всё это будет способствовать дальнейшему росту международного авторитета Туркменистана в качестве спортивного государства.
                            ',

            'content_en' => 'Bedenterbiýe we sport jemgyýetiň sagdynlygyny üpjün edýän gymmatlykdyr.
                            Türkmenistanda bu ulgamy ösdürmek döwlet syýasatynyň ileri tutulýan ugurlarynyň biri bolup durýar. Öňde goýlan wezipeleri amala aşyrmak maksady bilen, ýurtda bu ugurdaky hereketleriň täze usullary kemala getirilýär, ussat türgenleri taýýarlamak ugrunda toplumlaýyn özgertmeler amala aşyrylýar, Olimpiýa hereketiniň ösdürilmegine uly goşant goşulýar. Ýurdumyzda bedenterbiýäniň we sportuň kämilleşmegi, adamyň kuwwatynyň maddy we ruhy taýdan sazlaşykly utgaşmagy netijesinde sagdyn durmuş ýörelgelerine eýe bolmagy, şeýle-de sport boýunça halkara hyzmatdaşlygyň has-da giňelmegi döwlet syýasatynyň ileri tutulýan ugurlarynyň biri boldy.
                            Ýurduň ähli welaýatlarynda köpugurly stadionlar, bedenterbiýe we sagaldyş toplumlary, aýlawlar, sport mekdepleri we beýleki desgalar bina edildi we ulanmaga berildi. Türgenlerdir hünärmenleri, tälimçileri taýýarlamagyň täze usullary we sport oýunlaryny geçirmegiň tejribesi kämilleşdirildi. Türkmen sport ussatlary daşary ýurtlarda geçirilýän ýaryşlara işjeň gatnaşýarlar.
                            Türkmenistanda sportuň gyşky görnüşleri bilen meşgullanmaga hem giň mümkinçilikler döredilen. Aşgabatda Sportuň gyşky görnüşleri boýunça sport toplumy, Golf sport toplumy, dünýä ölçeglerine laýyk gelýän Türkmen döwlet bedenterbiýe we sport instituty, «Awaza» milli syýahatçylyk zolagynda uly göwrümli buz meýdançalaryndan ybarat bolan köpugurly sport toplumy guruldy. Ýurdumyzda hokkeý boýunça milli çempionat oýunlary geçirilýär, şeýle hem sportuň figuralaýyn buzda typmak we şort-trek ýaly görnüşleri ösdürilýär. Ýurdumyzda şaýbaly hokkeý boýunça hem çempionatlar geçirilýär. Türkmenistanyň hokkeý boýunça ýygyndy topary halkara derejesine çykdy.
                            Sport ulgamynda amala aşyrylýan özgertmeler sport ussatlygyň ýokary derejelere çykmagyna hem ýardam edýär. Bedenterbiýäniň we sportuň ösüşi «Bedenterbiýe we sport hakynda», «Professional sport hakynda», «Atçylyk we atçylyk sport ýaryşlary hakynda», «Ýaşlar barada döwlet syýasaty hakynda», «Meýletinçilik hakynda», şeýle-de «Sportda dopinge garşy göreş hakynda» Türkmenistanyň Kanunlarynda berkidilen.
                            Bu ugurda halkara hyzmatdaşlygyny has-da berkitmek, şeýle hem bütindünýä olimpiýa hereketine goşulyşmak üçin Türkmenistan BMG-niň Bilim, ylym we medeniýet boýunça ýöriteleşdirilen edarasynyň sportda doping serişdelerini ulanmaklyga garşy göreşi boýunça Halkara Konwensiýasyny tassyklady, Olimpiýa nyşanlaryny gorap saklamak baradaky Naýrobi ylalaşygyna goşuldy. Ýurtda Milli antidoping agentligi döredildi.
                            Türkmenistan halkara sport hyzmatdaşlygy düşünjesine ýokary ynsanperwer manyny berýär we ony gönüden-göni BMG-niň 2030-njy ýyla çenli Durnukly Ösüş Maksatlarynyň kabul edilmegi bilen baglanyşdyrýar. 2017-nji ýylyň 15-nji sentýabrynda BMG-niň Adam hukuklary boýunça geňeşiniň 36-njy mejlisinde Türkmenistanyň başlangyjy bilen, «Bosgunlaryň olimpik ýygyndysynyň parahatçylygy we adam hukuklaryny berkitmek boýunça gymmatly goşandyny höweslendirmek boýunça» atly ýüzlenme kabul edildi. Biziň ýurdumyzyň başlangyjy esasynda, BMG-niň Baş Assambleýasy 3-nji iýuny Bütindünýä welosiped güni hökmünde yglan etdi.
                            Türkmenistanda sportda netijeli halkara hyzmatdaşlygy alyp barmagyň düýp esaslary goýuldy. Şu babatda, 60-dan gowrak döwlet bilen ikitaraplaýyn esasda sport ulgamyndaky hyzmatdaşlyk hereketleri düzgünleşdirilýär. Bulardan başga-da, sport boýunça hyzmatdaşlyk meselesi döwlet baştutanlarynyň saparlarynyň dowamynda kabul edilýän jarnamalarda we beýannamalarda, şeýle hem ykdysady hyzmatdaşlygy ösdürmek boýunça hökümetara bilelikdäki toparlaryň jemleýji resminamalarynda öz mynasyp ornuny tapýar.
                            Halkara sport hyzmatdaşlygy ulgamynda hem-de sport diplomatiýasyny ösdürmek boýunça esasy möhüm ugurlaryň biri hem dünýäde türkmen milli göreşini yzygider ýaýratmak bolup durýar. 2015-nji ýyldan başlap Aşgabatda Bütindünýä göreş federasiýasynyň ştab-kwartirasy öz işine başlady. Sportuň bu görnüşi boýunça milli federasiýalar 20-den gowrak döwletde hereket edýär. 2017-nji ýylda Ýewropa, Afrika we Günorta Amerikanyň yklym federasiýalary döredildi we türkmen milli göreşi boýunça Ýewropanyň we Afrikanyň çempionatlary geçirildi. Türkmen milli göreşini dünýä ýaýratmak ugrundaky işler häzirki wagtda hem dowam etdirilýär.
                            Türkmenistan halkara sport hyzmatdaşlygynyň merkezleriniň biri hökmünde ykrar edildi. Bu işjeň hyzmatdaşlygyň çäklerinde Halkara Olimpiýa Komiteti, BMG-niň Ösüşiň we parahatçylygyň hatyrasyna sport boýunça halkara býurosy, ÝUNESKO-nyň Bedenterbiýe we sport boýunça hökümetara komiteti, Aziýanyň Olimpiýa Geňeşi bilen parahatçylygyň we ynsanperwerligiň pugtalandyrylmagyny şertlendirýän gatnaşyklaryň gerimi giňeýär.
                            2017-nji ýylyň 17-27-nji sentýabrynda Aşgabatda «Sagdynlyk. Ruhubelentlik. Dostluk» şygary astynda Ýapyk binalarda we söweş sungaty boýunça V Aziýa oýunlary geçirildi. «Aşgabat-2017-niň» ýaryşlaryna 45 sany Aziýa döwletlerinden hem-de Okeaniýanyň 19 döwletinden (dünýä döwletleriniň üçden bir bölegine barabar) türgenler gatnaşdy. Bu ýaryşlara bosgunlaryň sport topary hem şeýle derejedäki bäsleşige ilkinji gezek gatnaşdy.
                            Bäsleşikler Aşgabatda Oýunlar üçin ýörite gurlan, Merkezi Aziýa sebitinde deňi-taýy bolmadyk Olimpiýa şäherçesinde geçirildi. Şäherçede 40-dan gowrak dürli desgalar gurlyp, olaryň ikisi Ginnesiň Bütindünýä rekordlar kitabyna girizildi - Olimpiýa stadionynyň ýokarsynda ýerleşdirilen atyň dünýäde iň uly çeper-monumental şekili we dünýäde üsti ýapyk iň uly sportuň suw görnüşleriniň toplumydyr.
                            Geçirilen halkara derejesindäki iri ýaryşlaryň arasynda «Amul-Hazar-2018» awtorallisi, Agyr atletika boýunça 2018-nji ýylyň dünýä çempionaty, Beýik ýüpek ýolunuň ugry boýunça ylgaw ýaryşlary hem-de köpçülikleýin welosipedli ýörişler, Hazarýaka döwletleriň mekdep medeni-sport festiwaly we ş.m. bar. 2009-njy ýylda «Ýüpek ýoly» ralli ýaryşy geçirildi, onuň ýoly Türkmenistanyň, Gazagystanyň we Russiýanyň çäklerinden geçdi. 2014-nji ýylda «Awaza» milli syýahatçylyk zolagynda windsýorfing boýunça dünýä kubogy ugrundaky ýaryşyň tapgyrynyň geçirilmegi bilen, ýurdumyz ilkinji gezek ýelkenli sport boýunça halkara ýaryşlaryň senenamasyna girdi.
                            Ýaponiýada 2021-nji ýylda geçirilen XXXII tomusky Olimpiýa oýunlarynda Türkmenistanyň milli ýygyndy toparynyň türgenleriniň mynasyp wekilçilik etmekleri, ýurduň sport taryhynda ilkinji Olimpiýa medalynyň gazanylmagy döwletimizde sporty ösdürmäge uly üns berilýändigine şaýatlyk edýär. Türkmen döwlet bedenterbiýe we sport institutynda, Aşgabatdaky Olimpiýa şäherçesinde döredilen şertlerden hem-de innowasion mümkinçiliklerden ugur alyp, 2024-nji ýylda Parižde geçiriljek XXXIII tomusky Olimpiýa we XVII tomusky Paralimpiýa oýunlaryna, beýleki halkara ýaryşlara Türkmenistanyň milli ýygyndy toparlary taýynlyk görýärler.
                            Türkmenistan sebit we dünýäde rejesindäki iri sport ýaryşlary guramak hem-de geçirmek üçin uly tejribä hem mümkinçilige eýedir. Halkara ýaryşlara işjeň gatnaşýan türkmen türgenleriniň gazanýan üstünlikleri we ýeňişleri bu ulgamda durmuşa geçirilýän strategiýanyň netijeliliginiň aýdyň subutnamasydyr. Bularyň ählisi Türkmenistanyň dünýä derejesinde sport döwleti hökmünde abraýynyň has-da ýokarlanmagyna ýardam edýär.
                            ',
        ]);
    }
}
