<?php

namespace Database\Seeders;

use App\Models\TkmSocialSphere;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TkmSocialSphereSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        TkmSocialSphere::create([
            'title_tm' => 'DURMUŞ PUDAGY',
            'title_ru' => 'СОЦИАЛЬНАЯ СФЕРА',
            'title_en' => 'SOCIAL SPHERE',
            
            'content_tm' => 'Türkmenistanda «Döwlet – adam üçindir!» şygary bilen amala aşyrylýan düýpli durmuş özgertmeler syýasaty ilatyň ýaşaýyş şertleriniň ýokary derejede üpjün edilmegine gönükdirilendir. «Berkarar döwletiň täze eýýamynyň Galkynyşy: Türkmenistany 2022-2052-nji ýyllarda durmuş-ykdysady taýdan ösdürmegiň Milli maksatnamasy», «Türkmenistanyň Prezidentiniň ýurdumyzy 2022-2028-nji ýyllarda durmuş-ykdysady taýdan ösdürmegiň Maksatnamasy» ilatyň hal-ýagdaýyny gowulandyrmak boýunça giň möçberli taslamalary amala aşyrmaga esas bolup durýar. Şunuň bilen baglylykda, ýaşaýyş-durmuş meselelerini çözmek maksady bilen, köpsanly ýaşaýyş jaýlar, durmuş-hyzmat ediş toplumlar, hassahanalardyr şypahanalar, ýokary okuw jaýlaryň, mekdeplerdir çagalar baglarynyň binalary, döwrebap sport desgalar gurulýar.
                            Türkmenistanyň döwlet býujetiniň çykdajylarynyň 75-80 göterimi durmuş maksatly ugurlara, ýagny, saglygy goraýyş, bilim, medeniýet ulgamlaryny, ýaşaýyş jaý, jemagat hojalygyny maliýeleşdirmäge, zähmet haklarynyň, pensiýalaryň, döwlet kömek pullarynyň, talyp haklarynyň möçberleriniň köpeldilmegine, bu ugra degişli taslamalary amala aşyrmaga gönükdirilýär.
                            Türkmenistanda her ýyl aýlyk haklary, pensiýalar, döwlet kömek pullary, talyp haklary yzygiderli ýokarlandyrylýar. Dünýä ölçeglerine laýyklykda, ilat üçin ýaşaýyş-hyzmat we ulag hyzmatlaryna iň pes bahalar kesgitlenendir.
                            Raýatlaryň aýratyn toparlary, weteranlar we maýyplar, ata-enesiniň howandarlygyndan galan çagalar üçin goşmaça durmuş ýe­ňillikleri döredilýär. Türkmenistanyň 2013-nji ýylyň 1-nji ýanwaryndan güýje giren «Ilaty durmuş taýdan goramak hakyndaky» kodeksine laýyklykda, döwlet kömek pullarynyň we maýyplara durmuş kömekleriniň görnüşleri artdyryldy. Maýyplaryň kömek pullarynyň möçberi hem köpeldilýär.
                            Çaga dogulanda, üç ýaşa çenli oňa ideg etmek üçin berilýän döwlet kömek pullarynyň möçberi artýar. Ekleýjiniň bolmadyk halatynda hem döwlet tarapyndan kömek pullary berilýär. Şeýle-de durmuşy kömek pullarynyň berilmegine bolan hukugy göz öňüne tutulýar.
                            Döwlet syýasatynda raýatlaryň zähmet we iş üpjünçilik ugrundaky konstitusion hukuklarynyň berjaý edilmegi ugruna, ilaty iş bilen üpjün etmäge bu babatda olaryň goraglylygyna gönükdirilen çärelere hem uly ähmiýet berilýär - goşmaça iş orunlary döredilip, ilatyň iş üpjünçiligi ulgamy kämilleşdirilýär.
                            Türkmenistanda azyk harytlaryň, aýratyn hem, çagalar üçin niýetlenen önümleriň hiline we howpsuzlygyna berk gözegçilik ýola goýlan. Ilaty arassa agyz suwy bilen üpjün etmek boýunça alnyp barylýan işleriň gerimi giňeldildi. 2019-njy ýylda «Türkmenistanyň ilatynyň 2020-2025-nji ýyllarda sagdyn iýmitlenmegi boýunça Milli maksatnama» kabul edildi.
                            Türkmenistanda durmuş ähmiýetli harytlaryň we hyzmatlaryň bahalaryny, nyrhlaryny düzgünleşdirýän adalatly nyrh syýasaty alnyp barylýar. Ilatyň girdejilerini artdyrmak, zähmet öndürijiliginiň ösüş depginini zähmet haklarynyň ösüş depgini bilen utgaşdyryp alyp barmak, durmuş ulgamyna gönükdirilýän maýa goýum serişdeleriniň mukdaryny kesgitlenen möçberlerde üpjün etmek meselelerine wajyp ugurlaryň biri hökmünde ähmiýet berilýär. Ýurdumyzyň esasy durmuş-ykdysady ösüşiniň görkezijileri adam hakyndaky aladanyň döwlet syýasatynyň ileri tutulýan ugrudygyny tassyklaýar we raýatlaryň durmuş goraglylygynyň ýokary derejesini üpjün edýän ýurt hökmünde Türkmenistanyň halkara abraýyny has-da ýokarlandyrýar.
                            Birleşen Milletler Guramasynyň Durnukly ösüş maksatlaryny durmuşa geçirmegiň çäklerinde häzirki we geljekki nesilleriň bähbitleri üçin hem zerur işler alnyp barylýar. Türkmenistanda ilat elýeterli hem-de ýokary hilli lukmançylyk, bilim hyzmatlary bilen üpjün edilýär. «Sagdyn ene - sagdyn çaga - sagdyn geljek» atly Milli strategiýa esaslanmak bilen, durmuş ulgamynyň işinde netijeli çäreler ýola goýuldy.
                            ',

            'content_ru' => 'Политика коренных социальных преобразований, реализуемая в Туркменистана под девизом «Государство - для человека!», направлена на обеспечение высокого уровня благополучия населения. Задачи, определённые в Программе «Возрождение новой эпохи могущественного государства: Национальная программа социально-экономического развития Туркменистана в 2022-2052 годах» и «Программе Президента Туркменистана по социально-экономическому развитию страны в 2022-2028 годах», служат основанием для реализации широкомасштабных проектов по улучшению социально-бытового благосостояния народа.
                            В Туркменистане 75-80 процентов расходной части Государственного бюджета направляются на обеспечение социальной сферы – финансирование здравоохранения, образования, культуры, жилищного-коммунального фонда и сферы услуг, на увеличение заработных плат, пенсий, государственных пособий, стипендий, а также реализацию различных проектов в этом направлении. Ежегодно в Туркменистане повышаются заработные платы, пенсии, государственные пособия и стипендии. Для населения государством определены минимальные по мировым стандартам размеры жилищно-коммунальных и транспортных услуг.
                            Для отдельных категорий граждан, ветеранов и инвалидов, также детей, оставшихся без попечения родителей, создаются дополнительные социальные льготы. В соответствии с вступившим в силу с 1 января 2013 года Кодексом Туркменистана «О социальной защите населения», расширен перечень государственных пособий и видов социальной помощи инвалидам, увеличены размеры пособий по инвалидности. Установлено государственное пособие при рождении ребёнка и по уходу за ним до трёх лет. Предусмотрено пособие при потере кормильца, также предусмотрено право на получение социального пособия.
                            В государственной политике большое внимание уделяется конституционным правам граждан по обеспечению их работой, в этом направлении предпринимается комплекс мер: создаются дополнительные рабочие места, оптимизируется система трудоустройства населения.
                            В Туркменистане налажен строгий контроль за качеством и безопасностью продовольственных товаров, особенно, детского питания. Расширены рамки деятельности по обеспечению населения чистой питьевой водой. В 2019 году принята «Национальная программа по здоровому питанию населения Туркменистана на 2020-2025 годы».
                            В стране ведётся справедливая ценовая политика, регулирующая стоимость товаров и услуг социального назначения. Приоритетное значение придаётся увеличению доходов населения, координации темпов роста производительности труда и заработной платы, обеспечению установленного объёма инвестиций в социальную сферу. Основные индексы социально-экономического развития страны свидетельствуют, что главной целью государственной политики является забота о людях. Это выступает фактором роста международного авторитета Туркменистана, в котором обеспечивается высокий уровень социальной защищённости граждан.
                            В рамках достижения Целей устойчивого развития Организации Объединённых Наций предпринимаются необходимые меры, обусловленные интересами нынешнего и грядущих поколений. Население Туркменистана обеспечивается доступными и высококачественными медицинскими и образовательными услугами. В этом контексте, принятие Национальной стратегии «Здоровая мать – здоровый ребёнок – здоровое будущее» позволило ещё более оптимизировать деятельность социальной сферы.
                            ',

            'content_en' => 'Türkmenistanda «Döwlet – adam üçindir!» şygary bilen amala aşyrylýan düýpli durmuş özgertmeler syýasaty ilatyň ýaşaýyş şertleriniň ýokary derejede üpjün edilmegine gönükdirilendir. «Berkarar döwletiň täze eýýamynyň Galkynyşy: Türkmenistany 2022-2052-nji ýyllarda durmuş-ykdysady taýdan ösdürmegiň Milli maksatnamasy», «Türkmenistanyň Prezidentiniň ýurdumyzy 2022-2028-nji ýyllarda durmuş-ykdysady taýdan ösdürmegiň Maksatnamasy» ilatyň hal-ýagdaýyny gowulandyrmak boýunça giň möçberli taslamalary amala aşyrmaga esas bolup durýar. Şunuň bilen baglylykda, ýaşaýyş-durmuş meselelerini çözmek maksady bilen, köpsanly ýaşaýyş jaýlar, durmuş-hyzmat ediş toplumlar, hassahanalardyr şypahanalar, ýokary okuw jaýlaryň, mekdeplerdir çagalar baglarynyň binalary, döwrebap sport desgalar gurulýar.
                            Türkmenistanyň döwlet býujetiniň çykdajylarynyň 75-80 göterimi durmuş maksatly ugurlara, ýagny, saglygy goraýyş, bilim, medeniýet ulgamlaryny, ýaşaýyş jaý, jemagat hojalygyny maliýeleşdirmäge, zähmet haklarynyň, pensiýalaryň, döwlet kömek pullarynyň, talyp haklarynyň möçberleriniň köpeldilmegine, bu ugra degişli taslamalary amala aşyrmaga gönükdirilýär.
                            Türkmenistanda her ýyl aýlyk haklary, pensiýalar, döwlet kömek pullary, talyp haklary yzygiderli ýokarlandyrylýar. Dünýä ölçeglerine laýyklykda, ilat üçin ýaşaýyş-hyzmat we ulag hyzmatlaryna iň pes bahalar kesgitlenendir.
                            Raýatlaryň aýratyn toparlary, weteranlar we maýyplar, ata-enesiniň howandarlygyndan galan çagalar üçin goşmaça durmuş ýe­ňillikleri döredilýär. Türkmenistanyň 2013-nji ýylyň 1-nji ýanwaryndan güýje giren «Ilaty durmuş taýdan goramak hakyndaky» kodeksine laýyklykda, döwlet kömek pullarynyň we maýyplara durmuş kömekleriniň görnüşleri artdyryldy. Maýyplaryň kömek pullarynyň möçberi hem köpeldilýär.
                            Çaga dogulanda, üç ýaşa çenli oňa ideg etmek üçin berilýän döwlet kömek pullarynyň möçberi artýar. Ekleýjiniň bolmadyk halatynda hem döwlet tarapyndan kömek pullary berilýär. Şeýle-de durmuşy kömek pullarynyň berilmegine bolan hukugy göz öňüne tutulýar.
                            Döwlet syýasatynda raýatlaryň zähmet we iş üpjünçilik ugrundaky konstitusion hukuklarynyň berjaý edilmegi ugruna, ilaty iş bilen üpjün etmäge bu babatda olaryň goraglylygyna gönükdirilen çärelere hem uly ähmiýet berilýär - goşmaça iş orunlary döredilip, ilatyň iş üpjünçiligi ulgamy kämilleşdirilýär.
                            Türkmenistanda azyk harytlaryň, aýratyn hem, çagalar üçin niýetlenen önümleriň hiline we howpsuzlygyna berk gözegçilik ýola goýlan. Ilaty arassa agyz suwy bilen üpjün etmek boýunça alnyp barylýan işleriň gerimi giňeldildi. 2019-njy ýylda «Türkmenistanyň ilatynyň 2020-2025-nji ýyllarda sagdyn iýmitlenmegi boýunça Milli maksatnama» kabul edildi.
                            Türkmenistanda durmuş ähmiýetli harytlaryň we hyzmatlaryň bahalaryny, nyrhlaryny düzgünleşdirýän adalatly nyrh syýasaty alnyp barylýar. Ilatyň girdejilerini artdyrmak, zähmet öndürijiliginiň ösüş depginini zähmet haklarynyň ösüş depgini bilen utgaşdyryp alyp barmak, durmuş ulgamyna gönükdirilýän maýa goýum serişdeleriniň mukdaryny kesgitlenen möçberlerde üpjün etmek meselelerine wajyp ugurlaryň biri hökmünde ähmiýet berilýär. Ýurdumyzyň esasy durmuş-ykdysady ösüşiniň görkezijileri adam hakyndaky aladanyň döwlet syýasatynyň ileri tutulýan ugrudygyny tassyklaýar we raýatlaryň durmuş goraglylygynyň ýokary derejesini üpjün edýän ýurt hökmünde Türkmenistanyň halkara abraýyny has-da ýokarlandyrýar.
                            Birleşen Milletler Guramasynyň Durnukly ösüş maksatlaryny durmuşa geçirmegiň çäklerinde häzirki we geljekki nesilleriň bähbitleri üçin hem zerur işler alnyp barylýar. Türkmenistanda ilat elýeterli hem-de ýokary hilli lukmançylyk, bilim hyzmatlary bilen üpjün edilýär. «Sagdyn ene - sagdyn çaga - sagdyn geljek» atly Milli strategiýa esaslanmak bilen, durmuş ulgamynyň işinde netijeli çäreler ýola goýuldy.
                            ',
        ]);
    }
}
